
class JobStatus:
    PENDING = 'PENDING'
    QUEUED = 'QUEUED'
    PROCESSING = 'PROCESSING'
    FINALIZING = 'FINALIZING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'

    ALL = [PENDING, QUEUED, PROCESSING, FINALIZING, COMPLETED, FAILED]

class ItemStatus:
    PENDING = 'PENDING'
    QUEUED = 'QUEUED'
    PROCESSING = 'PROCESSING'
    FINALIZING = 'FINALIZING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    SKIPPED = 'SKIPPED'

    ALL = [PENDING, QUEUED, PROCESSING, FINALIZING, COMPLETED, FAILED, SKIPPED]
