# Generated by Django 5.0.14 on 2026-04-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('customerportal', '0001_initial'),
        ('masters', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerportal.customermastercustomerbasicdetails'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendormasterbasicdetail'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ledger',
            field=models.ForeignKey(blank=True, db_column='ledger_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_entries', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='bank_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_transactions', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='amounttransaction',
            name='ledger',
            field=models.ForeignKey(help_text='Reference to the Cash/Bank ledger', on_delete=django.db.models.deletion.CASCADE, related_name='amount_transactions', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='masterledgergroup',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subgroups', to='accounting.masterledgergroup'),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledgers', to='accounting.masterledgergroup'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(help_text='Customer from ledgers', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='voucher_type',
            field=models.ForeignKey(help_text='Sales voucher type', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.mastervoucherreceipts'),
        ),
        migrations.AddField(
            model_name='tenantledger',
            name='master_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounting.masterchartofaccounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['type', 'tenant_id', 'date'], name='vouchers_type_567f73_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['tenant_id', 'date'], name='vouchers_tenant__6180d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('tenant_id', 'type', 'voucher_number')},
        ),
        migrations.AddField(
            model_name='amounttransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='Reference to voucher if transaction is from a voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_transactions', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='vouchercreditnoteduedetails',
            name='credit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_details', to='accounting.vouchercreditnoteinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchercreditnoteitemdetails',
            name='credit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='accounting.vouchercreditnoteinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchercreditnoteitemline',
            name='item_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.vouchercreditnoteitemdetails'),
        ),
        migrations.AddField(
            model_name='vouchercreditnotetransitdetails',
            name='credit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_details', to='accounting.vouchercreditnoteinvoicedetails'),
        ),
        migrations.AddField(
            model_name='voucherdebitnoteitemline',
            name='item_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.voucherdebitnoteitemdetails'),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplierdetails',
            name='vendor_basic_detail',
            field=models.ForeignKey(db_column='vendor_basic_detail_id', on_delete=django.db.models.deletion.RESTRICT, related_name='debit_notes', to='vendors.vendormasterbasicdetail'),
        ),
        migrations.AddField(
            model_name='voucherdebitnoteitemdetails',
            name='debit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='accounting.voucherdebitnotesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherdebitnoteduedetails',
            name='debit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_details', to='accounting.voucherdebitnotesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherdebitnotetransitdetails',
            name='debit_note_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_details', to='accounting.voucherdebitnotesupplierdetails'),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='expense_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_items', to='accounting.voucherexpense'),
        ),
        migrations.AddField(
            model_name='journalvoucherentry',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_lines', to='accounting.voucherjournal'),
        ),
        migrations.AddField(
            model_name='voucherpurchaseadvancelink',
            name='due_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_links', to='accounting.voucherpurchaseduedetails'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplierdetails',
            name='vendor_basic_detail',
            field=models.ForeignKey(db_column='vendor_basic_detail_id', on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_vouchers', to='vendors.vendormasterbasicdetail'),
        ),
        migrations.AddField(
            model_name='voucherpurchaseitem',
            name='supplier_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounting.voucherpurchasesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherpurchaseduedetails',
            name='supplier_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_details', to='accounting.voucherpurchasesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplyforeigndetails',
            name='supplier_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_foreign_details', to='accounting.voucherpurchasesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplyinrdetails',
            name='supplier_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_inr_details', to='accounting.voucherpurchasesupplierdetails'),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='supplier_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_details', to='accounting.voucherpurchasesupplierdetails'),
        ),
        migrations.AddField(
            model_name='vouchersalesewaybill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill_details', to='accounting.vouchersalesinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchersalesdispatchdetails',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_details', to='accounting.vouchersalesinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchersalesitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.vouchersalesinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchersalesitemsforeign',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_items', to='accounting.vouchersalesinvoicedetails'),
        ),
        migrations.AddField(
            model_name='vouchersalespaymentdetails',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='accounting.vouchersalesinvoicedetails'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant_id', 'voucher_type', 'voucher_id'], name='entries_tenant__872c08_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant_id', 'ledger'], name='entries_tenant__83d9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['tenant_id', 'bank_ledger', 'status'], name='bank_statem_tenant__208430_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['tenant_id', 'transaction_date'], name='bank_statem_tenant__558d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['reference_number'], name='bank_statem_referen_11cffa_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['cheque_number'], name='bank_statem_cheque__9d0616_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['matched_voucher_id'], name='bank_statem_matched_04f046_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementtransaction',
            unique_together={('bank_ledger', 'transaction_date', 'reference_number', 'debit_amount', 'credit_amount')},
        ),
        migrations.AlterUniqueTogether(
            name='masterledgergroup',
            unique_together={('name', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='masterledger',
            unique_together={('name', 'tenant_id'), ('tenant_id', 'code')},
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant_id', 'invoice_date'], name='sales_invoi_tenant__62aed4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'tenant_id'], name='sales_invoi_custome_aa5d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['voucher_type'], name='sales_invoi_voucher_e4d47a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('tenant_id', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantledger',
            unique_together={('tenant_id', 'master_ledger')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'date'], name='transaction_tenant__69d40e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('tenant_id', 'voucher_number')},
        ),
        migrations.AddIndex(
            model_name='transactionallocation',
            index=models.Index(fields=['tenant_id', 'reference_number'], name='transaction_tenant__5ac850_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionallocation',
            index=models.Index(fields=['reference_type'], name='transaction_referen_b43917_idx'),
        ),
        migrations.AddIndex(
            model_name='amounttransaction',
            index=models.Index(fields=['tenant_id', 'ledger', 'transaction_date'], name='amount_tran_tenant__d7c201_idx'),
        ),
        migrations.AddIndex(
            model_name='amounttransaction',
            index=models.Index(fields=['tenant_id', 'transaction_type'], name='amount_tran_tenant__9534d3_idx'),
        ),
        migrations.AddIndex(
            model_name='amounttransaction',
            index=models.Index(fields=['transaction_date'], name='amount_tran_transac_10f4ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherpurchasesupplierdetails',
            unique_together={('supplier_invoice_no', 'gstin', 'tenant_id')},
        ),
    ]
