# Generated by Django 6.0 on 2026-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voucherconfiguration',
            name='voucher_con_effecti_a6b7a2_idx',
        ),
        migrations.RemoveField(
            model_name='mastervouchercontra',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervouchercontra',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervouchercreditnote',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervouchercreditnote',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherdebitnote',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherdebitnote',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherexpenses',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherexpenses',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherjournal',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherjournal',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherpayments',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherpayments',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherpurchases',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherpurchases',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervoucherreceipts',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervoucherreceipts',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervouchersales',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mastervouchersales',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='mastervouchersales',
            name='update_customer_master',
        ),
        migrations.AlterUniqueTogether(
            name='voucherconfiguration',
            unique_together={('tenant_id', 'voucher_type', 'voucher_name')},
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='outward_slip_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='voucherconfiguration',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='voucherconfiguration',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='voucherconfiguration',
            name='update_customer_master',
        ),
    ]
