# Generated by Django 5.0.14 on 2026-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentvoucher',
            unique_together={('tenant_id', 'voucher_number')},
        ),
        migrations.AlterUniqueTogether(
            name='receiptvoucher',
            unique_together={('tenant_id', 'voucher_number')},
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('tenant_id', 'type', 'voucher_number')},
        ),
        migrations.AddConstraint(
            model_name='paymentvoucheritem',
            constraint=models.UniqueConstraint(condition=models.Q(('advance_ref_no__isnull', False), models.Q(('advance_ref_no', ''), _negated=True)), fields=('tenant_id', 'advance_ref_no'), name='unique_payment_advance_ref'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucheritem',
            constraint=models.UniqueConstraint(condition=models.Q(('advance_ref_no__isnull', False), models.Q(('advance_ref_no', ''), _negated=True)), fields=('tenant_id', 'advance_ref_no'), name='unique_receipt_advance_ref'),
        ),
    ]
