# Generated by Django 5.0.14 on 2026-02-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        # DB already has renamed fields and added advance_references (from failed migration)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='vouchersalespaymentdetails',
                    old_name='payment_tcs',
                    new_name='payment_tds_gst',
                ),
                migrations.RenameField(
                    model_name='vouchersalespaymentdetails',
                    old_name='payment_tds',
                    new_name='payment_tds_income_tax',
                ),
                # This was likely JSONField before, now TextField. 
                # Since AddField fails if column exists, we fake the Add.
                # However, if type differs (JSON vs Text), we might need an Alter later.
                # Assuming simple string storage for now.
                migrations.AddField(
                    model_name='vouchersalespaymentdetails',
                    name='advance_references',
                    field=models.TextField(blank=True, default='[]', null=True),
                ),
            ]
        ),
        # Operations that might NOT be done or need explicit update
        migrations.RunSQL(
            "UPDATE voucher_sales_ewaybill SET eway_bill_available = '1' WHERE eway_bill_available = 'Yes';",
            "UPDATE voucher_sales_ewaybill SET eway_bill_available = 'Yes' WHERE eway_bill_available = '1';",
        ),
        migrations.RunSQL(
            "UPDATE voucher_sales_ewaybill SET eway_bill_available = '0' WHERE eway_bill_available != '1';",
        ),
        migrations.AlterField(
            model_name='vouchersalesewaybill',
            name='eway_bill_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vouchersalesewaybill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill_details', to='accounting.vouchersalesinvoicedetails'),
        ),
        # Ensure advance_references is TextField in DB (if it was JSONField)
        migrations.AlterField(
            model_name='vouchersalespaymentdetails',
            name='advance_references',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
