# Generated by Django 5.0.14 on 2026-04-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('ref_no', models.CharField(db_index=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjustment_date', models.DateField()),
                ('ledger_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('advance_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_out', to='accounting.voucher')),
                ('target_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_in', to='accounting.voucher')),
            ],
            options={
                'db_table': 'voucher_advance_adjustments',
                'unique_together': {('tenant_id', 'advance_voucher', 'target_voucher', 'ref_no')},
            },
        ),
    ]
