# Generated by Django 5.0.14 on 2026-04-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_paymentvoucheritem_advance_ref_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_voucher_id', models.BigIntegerField()),
                ('source_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt')], max_length=20)),
                ('target_voucher_id', models.BigIntegerField()),
                ('target_type', models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ledger', models.ForeignKey(db_column='ledger_id', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_allocations', to='accounting.masterledger')),
            ],
            options={
                'verbose_name': 'Voucher Allocation',
                'db_table': 'voucher_allocations',
                'indexes': [models.Index(fields=['tenant_id', 'ledger'], name='voucher_all_tenant__d2883b_idx'), models.Index(fields=['source_voucher_id', 'source_type'], name='voucher_all_source__3fb48b_idx'), models.Index(fields=['target_voucher_id', 'target_type'], name='voucher_all_target__97ecf0_idx')],
            },
        ),
    ]
