# Generated by Django 5.0.14 on 2026-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_payment_tcs_vouchersalespaymentdetails_payment_tds_gst_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vouchersalesewaybill',
                    name='ack_no',
                ),
                migrations.RemoveField(
                    model_name='vouchersalesewaybill',
                    name='irn',
                ),
            ]
        ),
    ]
