# Generated by Django 5.2.9 on 2026-02-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_voucherconfiguration_voucher_con_effecti_a6b7a2_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionfile',
            new_name='Transaction_tenant__8caf33_idx',
            old_name='Transcactio_tenant__f02ed7_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionfile',
            new_name='Transaction_tenant__8bb7a0_idx',
            old_name='Transcactio_tenant__99f3f8_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionfile',
            new_name='Transaction_ledger__aa65dd_idx',
            old_name='Transcactio_ledger__38f12f_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionfile',
            new_name='Transaction_nature_5be7e1_idx',
            old_name='Transcactio_nature_264db3_idx',
        ),
        migrations.AlterModelTable(
            name='transactionfile',
            table='Transaction_file',
        ),
    ]
