# Generated by Django 5.0.14 on 2026-04-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_paymentvoucheritem_advance_ref_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalespaymentdetails',
            name='payment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vouchersalespaymentdetails',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='vouchersalesinvoicedetails',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('received', 'Received'), ('partially received', 'Partially Received')], default='draft', max_length=20),
        ),
    ]
