# Generated by Django 5.0.14 on 2026-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_voucheradvanceadjustment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucheradvanceadjustment',
            old_name='ledger_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='voucheradvanceadjustment',
            name='vendor_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
