# Generated by Django 5.0.14 on 2026-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_vouchersalesewaybill_ack_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='ack_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='irn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
