# Generated by Django 5.0.14 on 2026-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_vouchersalesinvoicedetails_ack_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersalesinvoicedetails',
            name='ack_no',
        ),
        migrations.RemoveField(
            model_name='vouchersalesinvoicedetails',
            name='irn',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='vouchersalesewaybill',
                    name='ack_no',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='vouchersalesewaybill',
            name='irn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
