# Generated by Django 5.0.14 on 2026-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_ledger_id_voucheradvanceadjustment_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheradvanceadjustment',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
