# Generated by Django 5.0.14 on 2026-04-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_vendor_fks'),
        ('accounting', '0004_vouchersalespaymentdetails_payment_balance_and_more'),
    ]

    operations = [
    ]
