# Generated by Django 5.0.14 on 2026-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_voucheradvanceadjustment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpurchaseitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='voucheradvanceadjustment',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voucheradvanceadjustment',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
