# Generated by Django 5.0.14 on 2026-04-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_advanceallocationmap'),
        ('vendors', '0002_alter_vendormastertds_tcs_section_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amounttransaction',
            name='vendor',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendormasterbasicdetail'),
        ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='advance_source_type',
            field=models.CharField(choices=[('payment', 'Payment Voucher Item'), ('receipt', 'Receipt Voucher Item')], default='payment', help_text="'payment' or 'receipt'", max_length=20),
        ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales Invoice'), ('purchase', 'Purchase Invoice')], help_text="'sales' or 'purchase'", max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal'), ('debit_note', 'Debit Note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherpurchasesupplierdetails',
            name='vendor_basic_detail',
            field=models.ForeignKey(db_column='vendor_basic_detail_id', on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_vouchers', to='vendors.vendormasterbasicdetail'),
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteSupplierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('debit_note_series', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_note_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_invoice_nos', models.TextField(blank=True, help_text='Comma-separated Supplier Invoice Numbers', null=True)),
                ('purchase_voucher_nos', models.TextField(blank=True, help_text='Comma-separated Purchase Voucher Numbers', null=True)),
                ('purchase_voucher_dates', models.TextField(blank=True, help_text='Comma-separated Purchase Voucher Dates', null=True)),
                ('outward_slip_nos', models.TextField(blank=True, help_text='Comma-separated Outward Slip Numbers', null=True)),
                ('bill_to', models.TextField(blank=True, null=True)),
                ('ship_to', models.TextField(blank=True, null=True)),
                ('nature_of_supply', models.CharField(default='Regular', max_length=50)),
                ('reverse_charge', models.CharField(default='No', max_length=10)),
                ('place_of_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_in_foreign_currency', models.CharField(default='No', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('foreign_currency', models.CharField(default='USD', max_length=10)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='debit_note_documents/')),
                ('vendor_basic_detail', models.ForeignKey(db_column='vendor_basic_detail_id', on_delete=django.db.models.deletion.RESTRICT, related_name='debit_notes', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'db_table': 'voucher_debit_note_supplier_details',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteDueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reverse_tcs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reverse_tds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_it', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_invoice_amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('debit_note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_details', to='accounting.voucherdebitnotesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_debit_note_due_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteSupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debit_note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_details', to='accounting.voucherdebitnotesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_debit_note_supply_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteTransitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dispatch_from', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_transport', models.CharField(default='Road', max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('dispatch_time', models.TimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_id_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lr_gr_consignment_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_details', models.JSONField(blank=True, default=dict)),
                ('debit_note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_details', to='accounting.voucherdebitnotesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_debit_note_transit_details',
            },
        ),
    ]
