# Generated by Django 5.0.14 on 2026-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_voucherpurchaseitem_gst_rate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankstatementtransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bankstatementtransaction',
            name='bank_ledger',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='bank_reconcile_date',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='bank_reconciled',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='bank_reference_number',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='bank_statement_id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='source',
            field=models.CharField(default='manual', help_text='Source of voucher (e.g., manual, ocr)', max_length=100),
        ),
        migrations.DeleteModel(
            name='BankReconciliationLink',
        ),
        migrations.DeleteModel(
            name='BankStatementTransaction',
        ),
    ]
