# Generated by Django 5.0.14 on 2026-02-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_vouchersalesdispatchdetails_rail_beyond_port_fnr_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersalesdispatchdetails',
            name='rail_beyond_port_fnr_no',
        ),
        migrations.RemoveField(
            model_name='vouchersalesdispatchdetails',
            name='rail_upto_port_lr_gr_consignment',
        ),
        migrations.RemoveField(
            model_name='vouchersalesdispatchdetails',
            name='rail_upto_port_vehicle_no',
        ),
    ]
