# Generated by Django 5.0.14 on 2026-04-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_bankstatementtransaction_unique_together_and_more'),
    ]


    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='posting_note',
            field=models.TextField(blank=True, help_text='Per-row posting note entered in the allocation table', null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='posting_note',
            field=models.TextField(blank=True, help_text='Per-row posting note entered in the allocation table', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='posting_note',
            field=models.TextField(blank=True, help_text='Header-level posting note from the voucher form', null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='posting_note',
            field=models.TextField(blank=True, help_text='Per-row posting note entered in the allocation table', null=True),
        ),
    ]
