# Generated by Django 5.0.14 on 2026-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_amounttransaction_vendor_journalentry_vendor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_dest_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_final_dest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_port_of_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_port_of_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_sb_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_sb_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_ship_port_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='beyond_port_vessel_flight_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_dest_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_final_dest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_rail_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_rr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_rr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_station_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_beyond_station_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_upto_delivery_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_upto_transporter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='rail_upto_transporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_final_dest_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_final_dest_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_fnr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_port_of_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_port_of_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_rr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_rr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_station_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_station_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='upto_port_vessel_flight_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
