# Generated by Django 5.0.14 on 2026-02-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_vouchersalesdispatchdetails_rail_beyond_port_fnr_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesdispatchdetails',
            name='rail_beyond_port_fnr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesdispatchdetails',
            name='rail_upto_port_lr_gr_consignment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesdispatchdetails',
            name='rail_upto_port_vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
