# Generated by Django 5.0.14 on 2026-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_posting_note_to_transaction_and_allocation'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE advance_allocation MODIFY amount DECIMAL(25,2)"),
        migrations.RunSQL("ALTER TABLE advance_allocation MODIFY advance DECIMAL(25,2)"),
        migrations.AlterField(
            model_name='advanceallocation',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='pending_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='amounttransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this transaction', max_digits=25),
        ),
        migrations.AlterField(
            model_name='amounttransaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (money going out)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='amounttransaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Debit amount (money coming in)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance amount for this ledger', max_digits=25),
        ),
        migrations.RunSQL("ALTER TABLE pending_transaction MODIFY amount DECIMAL(25,2)"),
        migrations.RunSQL("ALTER TABLE pending_transaction MODIFY advance DECIMAL(25,2)"),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='pending_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.RunSQL("ALTER TABLE transaction_allocations MODIFY amount DECIMAL(25,2)"),
        migrations.RunSQL("ALTER TABLE transaction_allocations MODIFY advance DECIMAL(25,2)"),
        migrations.AlterField(
            model_name='transactionallocation',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='pending_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='voucheradvanceadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
