# Generated by Django 5.0.14 on 2026-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_delete_answer_delete_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='financial_reporting_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='financial_reporting_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='ledger_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='major_group_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='sub_group_1_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='sub_group_2_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='sub_group_3_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='type_of_business_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterhierarchyraw',
            name='type_of_business_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='financial_reporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='major_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='type_of_business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
