# Generated by Django 5.0.14 on 2026-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_vouchercreditnoteduedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
