# Generated by Django 5.0.14 on 2026-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_paymentvoucheritem_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherallocation',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='reference_type',
            field=models.CharField(default='INVOICE', max_length=50),
        ),
        migrations.AlterField(
            model_name='voucherallocation',
            name='target_voucher_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
