# Generated by Django 5.0.14 on 2026-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_voucher_bank_reconcile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vouch_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount entered in the voucher header', max_digits=25),
        ),
    ]
