# Generated by Django 5.0.14 on 2026-04-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_masterhierarchyraw_financial_reporting_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='vendor',
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together=None,
        ),
    ]
