# Generated by Django 5.0.14 on 2026-04-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_journalentry_customer_and_more'),
        ('company', '0001_initial'),
        ('transactions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounttransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='Reference to voucher if transaction is from a voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_transactions', to='transactions.voucher'),
        ),
        migrations.RemoveField(
            model_name='vouchersalesdispatchdetails',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='vouchersalesewaybill',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='vouchersalesitemsforeign',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='vouchersalesitems',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='vouchersalespaymentdetails',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='advanceallocationmap',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='amounttransaction',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='bankreconciliationlink',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='bankstatementtransaction',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='extractedinvoice',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='masterledger',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='masterledgergroup',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenantledger',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherallocation',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='vouchercontra',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnoteduedetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplierdetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotetransitdetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherexpense',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseduedetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasesupplierdetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasesupplyforeigndetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasesupplyinrdetails',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasetransitdetails',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='advanceallocationmap',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='amounttransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='bankreconciliationlink',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='extractedinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='masterledgergroup',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='tenantledger',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='vouchercontra',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherdebitnoteduedetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplierdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherdebitnotetransitdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherjournal',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherpurchaseduedetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplierdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplyforeigndetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherpurchasesupplyinrdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='voucherpurchasetransitdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherSalesDispatchDetails',
        ),
        migrations.DeleteModel(
            name='VoucherSalesEwayBill',
        ),
        migrations.DeleteModel(
            name='VoucherSalesItemsForeign',
        ),
        migrations.DeleteModel(
            name='VoucherSalesItems',
        ),
        migrations.DeleteModel(
            name='VoucherSalesInvoiceDetails',
        ),
        migrations.DeleteModel(
            name='VoucherSalesPaymentDetails',
        ),
    ]
