# Generated by Django 5.0.14 on 2026-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_voucherallocation_balance_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherallocation',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='voucherallocation',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='source_voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='source_voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='target_voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='target_voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
