# Generated by Django 5.0.14 on 2026-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_voucherallocation_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheritem',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherallocation',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
