# Generated by Django 5.0.14 on 2026-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_voucher_bank_reconcile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='bank_reconcile_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='bank_reconciled',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='bank_reference_number',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='bank_statement_id',
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='amount',
            field=models.DecimalField(db_column='advance', decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='allocated_amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(db_column='advance', decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='allocated_amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='amount',
            field=models.DecimalField(db_column='advance', decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocated_amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=25),
        ),
    ]
