# Generated by Django 5.0.14 on 2026-04-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_vouchersalesinvoicedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterledger',
            name='additional_data',
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='extended_data',
            field=models.JSONField(blank=True, help_text='Deprecated: Use LedgerAttribute table', null=True),
        ),
        migrations.AlterField(
            model_name='voucherpurchasesupplyinrdetails',
            name='items',
            field=models.JSONField(default=list, help_text='Deprecated: Use VoucherPurchaseItem relation'),
        ),
        migrations.CreateModel(
            name='VoucherPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('supply_foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='accounting.voucherpurchasesupplyforeigndetails')),
                ('supply_inr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='accounting.voucherpurchasesupplyinrdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_items',
            },
        ),
        migrations.CreateModel(
            name='LedgerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='accounting.masterledger')),
            ],
            options={
                'db_table': 'master_ledger_attributes',
                'unique_together': {('ledger', 'key')},
            },
        ),
    ]
