# Generated by Django 5.0.14 on 2026-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_voucher_bank_reconcile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='reference_no',
            field=models.CharField(blank=True, help_text='External/Bank reference number', max_length=100, null=True),
        ),
    ]
