# Generated by Django 5.0.14 on 2026-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_paymentvoucher_ledger_id_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
