# Generated by Django 5.0.14 on 2026-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_voucher_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Unified Reference Number (UPI/Chq/IMPS)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Unified Reference Number (UPI/Chq/IMPS)', max_length=100, null=True),
        ),
    ]
