# Generated by Django 5.0.14 on 2026-04-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_masterledger_additional_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalVoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ledger_name', models.CharField(max_length=255)),
                ('ledger_id', models.BigIntegerField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entry_note', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'norm_journal_voucher_entries',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_advance', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'norm_payment_allocations',
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_advance', models.BooleanField(default=False)),
                ('advance_ref_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'norm_receipt_allocations',
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason_for_return', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'norm_debit_note_line_items',
            },
        ),
        migrations.CreateModel(
            name='VoucherExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_ledger', models.CharField(max_length=255)),
                ('post_to_ledger', models.CharField(max_length=255)),
                ('bill_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_note', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('posting_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voucher Expense Item',
                'verbose_name_plural': 'Voucher Expense Items',
                'db_table': 'norm_expense_line_items',
            },
        ),
        migrations.RemoveConstraint(
            model_name='receiptvoucheritem',
            name='unique_receipt_advance_ref',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='advance_ref_no',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='balance_after',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='is_advance',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='pending_before',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='received_amount',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_cess',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_cgst',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_igst',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_invoice_value',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_sgst',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='total_taxable_value',
        ),
        migrations.RemoveField(
            model_name='voucherexpense',
            name='posting_note',
        ),
        migrations.AlterField(
            model_name='paymentvoucheritem',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='Deprecated: Use PaymentAllocationDetail table', null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucheritem',
            name='pending_transaction',
            field=models.JSONField(blank=True, help_text='Deprecated: Use ReceiptAllocationDetail table', null=True),
        ),
        migrations.AlterField(
            model_name='voucherdebitnotesupplydetails',
            name='items',
            field=models.JSONField(default=list, help_text='Deprecated: Use VoucherDebitNoteItem table'),
        ),
        migrations.AlterField(
            model_name='voucherexpense',
            name='expense_rows',
            field=models.JSONField(default=list, help_text='Deprecated: Use VoucherExpenseItem table'),
        ),
        migrations.AlterField(
            model_name='voucherexpense',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded supporting document filenames'),
        ),
        migrations.AlterField(
            model_name='voucherjournal',
            name='entries',
            field=models.JSONField(default=list, help_text='Deprecated: Use JournalVoucherEntry table'),
        ),
        migrations.AlterModelTable(
            name='receiptvoucheritem',
            table='norm_receipt_line_items',
        ),
        migrations.AlterModelTable(
            name='voucherdebitnotesupplydetails',
            table='norm_debit_note_supply_headers',
        ),
        migrations.AddField(
            model_name='journalvoucherentry',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_lines', to='accounting.voucherjournal'),
        ),
        migrations.AddField(
            model_name='paymentallocationdetail',
            name='payment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.paymentvoucheritem'),
        ),
        migrations.AddField(
            model_name='receiptallocationdetail',
            name='receipt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.receiptvoucheritem'),
        ),
        migrations.AddField(
            model_name='voucherdebitnoteitem',
            name='supply_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.voucherdebitnotesupplydetails'),
        ),
        migrations.AddField(
            model_name='voucherexpenseitem',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.voucherexpense'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocationdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('advance_ref_no__isnull', False), models.Q(('advance_ref_no', ''), _negated=True)), fields=('tenant_id', 'advance_ref_no'), name='unique_receipt_advance_ref'),
        ),
    ]
