# Generated by Django 5.0.14 on 2026-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_journalentry_reference_no_transaction_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Reference Number (Cheque, NEFT, etc)', max_length=150, null=True),
        ),
    ]
