# Generated by Django 5.0.14 on 2026-04-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_journalvoucherentry_paymentallocationdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPurchaseAdvanceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('ref_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('applied_now', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'voucher_purchase_advance_links',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ledgerattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ledgerattribute',
            name='ledger',
        ),
        migrations.RemoveConstraint(
            model_name='receiptallocationdetail',
            name='unique_receipt_advance_ref',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='cess_rate',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='cgst_rate',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='igst_rate',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='sgst_rate',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='supply_foreign',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseitem',
            name='supply_inr',
        ),
        migrations.AddField(
            model_name='masterledger',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Stores answers to dynamic questions (e.g., opening balance, GSTIN, credit limit)', null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='pending_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptvoucheritem',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdebitnotesupplydetails',
            name='total_taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='posting_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherpurchaseitem',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='voucherpurchaseitem',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucherpurchaseitem',
            name='supplier_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounting.voucherpurchasesupplierdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='extended_data',
            field=models.JSONField(blank=True, help_text='Group-specific fields (e.g., cashLocation, loanAccountNumber)', null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucheritem',
            name='transaction_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucheritem',
            name='pending_transaction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucherdebitnotesupplydetails',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='voucherexpense',
            name='expense_rows',
            field=models.JSONField(default=list, help_text='List of expense entries'),
        ),
        migrations.AlterField(
            model_name='voucherexpense',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list, help_text=' List of uploaded supporting document filenames'),
        ),
        migrations.AlterField(
            model_name='voucherjournal',
            name='entries',
            field=models.JSONField(default=list, help_text='List of journal entries'),
        ),
        migrations.AlterField(
            model_name='voucherpurchaseitem',
            name='item_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpurchaseitem',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpurchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucherpurchaseitem',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpurchasesupplyinrdetails',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucheritem',
            constraint=models.UniqueConstraint(condition=models.Q(('advance_ref_no__isnull', False), models.Q(('advance_ref_no', ''), _negated=True)), fields=('tenant_id', 'advance_ref_no'), name='unique_receipt_advance_ref'),
        ),
        migrations.AlterModelTable(
            name='receiptvoucheritem',
            table='receipt_voucher_items',
        ),
        migrations.AddField(
            model_name='voucherpurchaseadvancelink',
            name='due_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_links', to='accounting.voucherpurchaseduedetails'),
        ),
        migrations.DeleteModel(
            name='LedgerAttribute',
        ),
    ]
