# Generated by Django 5.0.14 on 2026-04-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_voucherpurchaseadvancelink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_ledger_name', models.CharField(max_length=255)),
                ('expense_ledger_id', models.BigIntegerField(blank=True, null=True)),
                ('post_to_ledger_name', models.CharField(max_length=255)),
                ('post_to_ledger_id', models.BigIntegerField(blank=True, null=True)),
                ('bill_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_note', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_items', to='accounting.voucherexpense')),
            ],
            options={
                'db_table': 'norm_voucher_expense_items',
            },
        ),
        migrations.DeleteModel(
            name='VoucherExpenseItem',
        ),
    ]
