# Generated by Django 5.0.14 on 2026-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_remove_journalentry_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Reference Number (Cheque, NEFT, etc)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Reference Number (Cheque, NEFT, etc)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Reference Number (Cheque, NEFT, etc)', max_length=150, null=True),
        ),
    ]
