# Generated by Django 5.0.14 on 2026-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_advanceallocation_ref_no_pendingtransaction_ref_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Reference Number (Cheque, NEFT, etc)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
