# Generated by Django 5.0.14 on 2026-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_advanceallocation_ref_no_pendingtransaction_ref_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='narration',
            field=models.TextField(blank=True, help_text='Original narration from bank upload or source', null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='narration',
            field=models.TextField(blank=True, help_text='Original narration from bank upload or source', null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='narration',
            field=models.TextField(blank=True, help_text='Original narration from bank upload or source', null=True),
        ),
    ]
