# Generated by Django 5.0.14 on 2026-04-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_expenselineitem_delete_voucherexpenseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='items_data',
        ),
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='items',
        ),
        migrations.RemoveField(
            model_name='voucherexpense',
            name='expense_rows',
        ),
        migrations.RemoveField(
            model_name='voucherjournal',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='voucherpurchaseduedetails',
            name='advance_references',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasesupplyforeigndetails',
            name='items',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasesupplyinrdetails',
            name='items',
        ),
        migrations.RemoveField(
            model_name='voucherpurchasetransitdetails',
            name='extra_details',
        ),
        migrations.RemoveField(
            model_name='vouchersalespaymentdetails',
            name='advance_references',
        ),
    ]
