# Generated by Django 5.0.14 on 2026-05-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_advanceallocation_narration_and_more'),
        ('accounting', '0017_voucher_ref_no_and_more'),
    ]

    operations = [
    ]
