# Generated by Django 5.0.14 on 2026-05-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_merge_20260507_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='allocation_status',
            field=models.CharField(default='Unutilized', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
