# Generated by Django 5.0.14 on 2026-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_merge_accounting_heads'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='voucherdebitnotesupplydetails',
        #     name='items',
        # ),
        migrations.AlterField(
            model_name='advanceallocationmap',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='allocationlink',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercreditnoteduedetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercreditnoteinvoicedetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercreditnoteitemdetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercreditnotetransitdetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='voucherdebitnoteduedetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='voucherdebitnotesupplierdetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        # migrations.AlterField(
        #     model_name='voucherdebitnotesupplydetails',
        #     name='tenant_id',
        #     field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        # ),
        migrations.AlterField(
            model_name='voucherdebitnotetransitdetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        # migrations.AlterModelTable(
        #     name='voucherdebitnotesupplydetails',
        #     table='norm_debit_note_supply_headers',
        # ),
    ]
