# Generated by Django 5.0.14 on 2026-04-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_remove_voucherdebitnotesupplydetails_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='items',
        ),
        migrations.AlterField(
            model_name='voucherdebitnotesupplydetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterModelTable(
            name='transactionfile',
            table='transaction_file',
        ),
        migrations.AlterModelTable(
            name='voucherdebitnotesupplydetails',
            table='norm_debit_note_supply_headers',
        ),
    ]
