# Generated by Django 5.0.14 on 2026-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_journalentry_allocation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
