# Generated by Django 5.0.14 on 2026-05-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_merge_20260507_1509'),
        ('accounting', '0020_alter_advanceallocation_allocated_amount_and_more'),
    ]

    operations = [
    ]
