# Generated by Django 5.0.14 on 2026-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_remove_voucherdebitnotesupplydetails_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucheritem',
            name='transaction_details',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='pending_transaction',
        ),
        migrations.AlterField(
            model_name='allocationlink',
            name='source_reference_type',
            field=models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationlink',
            name='target_reference_type',
            field=models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='reference_type',
            field=models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
    ]
