# Generated by Django 5.0.14 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_paymentvoucheritem_transaction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='payment_voucher_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receipt_voucher_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='sales_voucher_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
