# Generated by Django 5.0.14 on 2026-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_merge_20260512_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceallocation',
            name='allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='advanceallocation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
