# Generated by Django 5.0.14 on 2026-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_advanceallocation_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='amendment_date',
            field=models.DateField(blank=True, help_text='Date when this voucher was amended after being GST filed', null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Flag indicating if this voucher has been filed in GST'),
        ),
    ]
