# Generated by Django 5.0.14 on 2026-04-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_pendingtransaction_payment_voucher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptallocationdetail',
            name='receipt_item',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='payment_voucher_id',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='receipt_voucher_id',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='sales_voucher_id',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='allocationlink',
            name='source_reference_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationlink',
            name='target_reference_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='reference_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('REVERSAL', 'Reversal Entry')], max_length=20),
        ),
        migrations.CreateModel(
            name='VoucherPendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_advance', models.BooleanField(default=False)),
                ('advance_ref_no', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='accounting.paymentvoucheritem')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='accounting.receiptvoucheritem')),
            ],
            options={
                'db_table': 'voucher_pending_transactions',
            },
        ),
        migrations.DeleteModel(
            name='PaymentAllocationDetail',
        ),
        migrations.DeleteModel(
            name='ReceiptAllocationDetail',
        ),
        migrations.AddIndex(
            model_name='voucherpendingtransaction',
            index=models.Index(fields=['tenant_id', 'invoice_no'], name='voucher_pen_tenant__aa361a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherpendingtransaction',
            index=models.Index(fields=['payment_item'], name='voucher_pen_payment_e373a7_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherpendingtransaction',
            index=models.Index(fields=['receipt_item'], name='voucher_pen_receipt_179108_idx'),
        ),
    ]
