# Generated by Django 5.0.14 on 2026-06-20 08:40

from django.db import migrations, models


def backfill_normalized_invoice_no(apps, schema_editor):
    VoucherPurchaseSupplierDetails = apps.get_model('accounting', 'VoucherPurchaseSupplierDetails')
    from vendors.vendor_validation_logic import normalize_invoice_number
    
    for obj in VoucherPurchaseSupplierDetails.objects.all():
        if obj.supplier_invoice_no:
            obj.normalized_invoice_no = normalize_invoice_number(obj.supplier_invoice_no)
            obj.save(update_fields=['normalized_invoice_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_advanceallocation_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpurchasesupplierdetails',
            name='normalized_invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(backfill_normalized_invoice_no, migrations.RunPython.noop),
    ]

