# Generated by Django 5.0.14 on 2026-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_vouchersalesinvoicedetails_amendment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersalesinvoicedetails',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this voucher has been filed in GST, empty otherwise", max_length=3),
        ),
    ]
