# Generated by Django 5.0.14 on 2026-04-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_refactor_payment_receipt_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('payment_single', 'Payment – Single'), ('payment_bulk', 'Payment – Bulk'), ('receipt_single', 'Receipt – Single'), ('receipt_bulk', 'Receipt – Bulk')], db_index=True, help_text='payment_single | payment_bulk | receipt_single | receipt_bulk', max_length=20)),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('pay_from_ledger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_to_ledger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('advance_ref_no', models.CharField(blank=True, help_text='User-entered advance reference number', max_length=150, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Full voucher total', max_digits=15)),
                ('bank_reconciled', models.BooleanField(default=False)),
                ('bank_reconcile_date', models.DateField(blank=True, null=True)),
                ('bank_statement_id', models.BigIntegerField(blank=True, null=True)),
                ('bank_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='manual', help_text="'manual' | 'bulk' | 'ai_extracted'", max_length=100)),
            ],
            options={
                'verbose_name': 'Advance Allocation',
                'verbose_name_plural': 'Advance Allocations',
                'db_table': 'advance_allocations',
            },
        ),
        migrations.DeleteModel(
            name='AdvanceAllocationMap',
        ),
        migrations.DeleteModel(
            name='AllocationLink',
        ),
        migrations.AlterUniqueTogether(
            name='paymentvoucher',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='pay_from',
        ),
        migrations.RemoveField(
            model_name='paymentvoucheritem',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='paymentvoucheritem',
            name='pay_to_ledger',
        ),
        migrations.RemoveField(
            model_name='voucherpendingtransaction',
            name='payment_item',
        ),
        migrations.AlterUniqueTogether(
            name='receiptvoucher',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='receive_in',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheritem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='voucherpendingtransaction',
            name='receipt_item',
        ),
        migrations.RemoveField(
            model_name='voucherallocation',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='VoucherReceiptBulk',
        ),
        migrations.DeleteModel(
            name='VoucherReceiptSingle',
        ),
        migrations.RemoveIndex(
            model_name='pendingtransaction',
            name='pending_tra_tenant__e96444_idx',
        ),
        migrations.RenameField(
            model_name='pendingtransaction',
            old_name='pending_balance',
            new_name='amount_applied',
        ),
        migrations.RenameField(
            model_name='pendingtransaction',
            old_name='reference_date',
            new_name='due_date',
        ),
        migrations.RenameIndex(
            model_name='pendingtransaction',
            new_name='pt_vendor_idx',
            old_name='pending_tra_tenant__e4ed55_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingtransaction',
            new_name='pt_customer_idx',
            old_name='pending_tra_tenant__2ee310_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pendingtransaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='days_to_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, db_column='pay_from_ledger_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_pay_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_ledger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, db_column='pay_to_ledger_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_pay_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_ledger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='type',
            field=models.CharField(choices=[('payment_single', 'Payment – Single'), ('payment_bulk', 'Payment – Bulk'), ('receipt_single', 'Receipt – Single'), ('receipt_bulk', 'Receipt – Bulk')], db_index=True, default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bank_reconcile_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bank_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bank_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bank_statement_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Major group / category (e.g. Asset, Liability)', max_length=255),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='group',
            field=models.CharField(blank=True, help_text='Ledger group name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('advance', 'Advance'), ('on_account', 'On Account'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], default='invoice', max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='vendor_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['tenant_id', 'type'], name='pt_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['tenant_id', 'voucher_number'], name='pt_voucher_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['tenant_id', 'voucher_date'], name='pt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['tenant_id', 'reference_number'], name='pt_refno_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['tenant_id', 'status'], name='pt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['pay_from_ledger'], name='pt_payfrom_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransaction',
            index=models.Index(fields=['pay_to_ledger'], name='pt_payto_idx'),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, db_column='pay_from_ledger_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_pay_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, db_column='pay_to_ledger_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_pay_to', to='accounting.masterledger'),
        ),
        migrations.DeleteModel(
            name='PaymentVoucher',
        ),
        migrations.DeleteModel(
            name='PaymentVoucherItem',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucher',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucherItem',
        ),
        migrations.DeleteModel(
            name='VoucherPendingTransaction',
        ),
        migrations.DeleteModel(
            name='VoucherAllocation',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='purchase_voucher_id',
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['tenant_id', 'type'], name='adv_alloc_type_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['tenant_id', 'voucher_number'], name='adv_alloc_vno_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['tenant_id', 'advance_ref_no'], name='adv_alloc_refno_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['tenant_id', 'vendor_id'], name='adv_alloc_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['tenant_id', 'customer_id'], name='adv_alloc_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['pay_from_ledger'], name='adv_alloc_pay_from_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceallocation',
            index=models.Index(fields=['pay_to_ledger'], name='adv_alloc_pay_to_idx'),
        ),
    ]
