# Generated by Django 5.0.14 on 2026-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_gst_registered_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='original_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the voucher before the first amendment', null=True),
        ),
    ]
