# Generated by Django 5.0.14 on 2026-06-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_vouchersalesinvoicedetails_original_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersalesinvoicedetails',
            name='original_snapshot',
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='original_voucher_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the original voucher before amendment', null=True),
        ),
    ]
