# Generated by Django 5.0.14 on 2026-04-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_add_bank_rec_to_vouchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceallocation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='pay_from_ledger_name',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='pay_to_ledger_name',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='pay_from_ledger_name',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='pay_to_ledger_name',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='vendor_name',
        ),
    ]
