# Generated by Django 5.0.14 on 2026-04-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_remove_name_fields_from_unified_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherdebitnotesupplydetails',
            name='debit_note_details',
        ),
        migrations.RemoveField(
            model_name='vouchercreditnoteitemdetails',
            name='items',
        ),
        migrations.CreateModel(
            name='VoucherCreditNoteItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason_for_return', models.TextField(blank=True, null=True)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.vouchercreditnoteitemdetails')),
            ],
            options={
                'db_table': 'voucher_credit_note_item_lines',
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debit_note_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='accounting.voucherdebitnotesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_debit_note_item_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitNoteItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason_for_return', models.TextField(blank=True, null=True)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='accounting.voucherdebitnoteitemdetails')),
            ],
            options={
                'db_table': 'voucher_debit_note_item_lines',
            },
        ),
        migrations.DeleteModel(
            name='VoucherDebitNoteItem',
        ),
        migrations.DeleteModel(
            name='VoucherDebitNoteSupplyDetails',
        ),
    ]
