# Generated by Django 5.0.14 on 2026-06-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_voucherpurchasesupplierdetails_normalized_invoice_no'),
        ('accounting', '0026_remove_vouchersalesinvoicedetails_original_snapshot_and_more'),
    ]

    operations = [
    ]
