# Generated by Django 5.0.14 on 2026-04-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_remove_voucherdebitnotesupplydetails_debit_note_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voucher_number', models.CharField(db_index=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('narration', models.TextField(blank=True, null=True)),
                ('bank_reconciled', models.BooleanField(default=False)),
                ('bank_reconcile_date', models.DateField(blank=True, null=True)),
                ('bank_statement_id', models.BigIntegerField(blank=True, null=True)),
                ('bank_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_id_val', models.BigIntegerField(blank=True, null=True)),
                ('party_customer_id', models.BigIntegerField(blank=True, null=True)),
                ('party_vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('pay_from_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_from', to='accounting.masterledger')),
                ('pay_to_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_to', to='accounting.masterledger')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reference_number', models.CharField(db_index=True, max_length=150)),
                ('reference_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('ADVANCE', 'Advance'), ('ON_ACCOUNT', 'On Account')], default='INVOICE', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('pending_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.transaction')),
            ],
            options={
                'db_table': 'transaction_allocations',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'date'], name='transaction_tenant__69d40e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('tenant_id', 'voucher_number')},
        ),
        migrations.AddIndex(
            model_name='transactionallocation',
            index=models.Index(fields=['tenant_id', 'reference_number'], name='transaction_tenant__5ac850_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionallocation',
            index=models.Index(fields=['reference_type'], name='transaction_referen_b43917_idx'),
        ),
    ]
