# Generated by Django 5.0.14 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_merge_20260629_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreditnoteinvoicedetails',
            name='gst_registered',
            field=models.CharField(blank=True, default='', help_text="'Yes' if this voucher has been filed in GST, empty otherwise", max_length=3),
        ),
    ]
