# Generated by Django 5.0.14 on 2026-04-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_transaction_transactionallocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='pay_from_ledger',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='pay_to_ledger',
        ),
        migrations.DeleteModel(
            name='AdvanceAllocation',
        ),
        migrations.DeleteModel(
            name='PendingTransaction',
        ),
    ]
