# Generated by Django 5.0.14 on 2026-04-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_remove_pendingtransaction_pay_from_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='allocations_from', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='allocations_to', to='accounting.masterledger'),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
