# Generated by Django 5.0.14 on 2026-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_transactionallocation_pay_from_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='transaction_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
