# Generated by Django 5.0.14 on 2026-04-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_transactionallocation_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='party_vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
