# Generated by Django 5.0.14 on 2026-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_transactionallocation_ledger_id_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionallocation',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
