# Generated by Django 5.0.14 on 2026-04-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_alter_transactionallocation_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger'),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='pay_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger'),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction'),
        ),
        migrations.CreateModel(
            name='AdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('reference_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('ADVANCE', 'Advance'), ('ON_ACCOUNT', 'On Account')], default='INVOICE', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_details', models.JSONField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('pending_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ledger_id_val', models.BigIntegerField(blank=True, null=True)),
                ('party_customer_id', models.BigIntegerField(blank=True, null=True)),
                ('party_vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('pay_from_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger')),
                ('pay_to_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction')),
            ],
            options={
                'db_table': 'advance_allocation',
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('reference_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('ADVANCE', 'Advance'), ('ON_ACCOUNT', 'On Account')], default='INVOICE', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_details', models.JSONField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('pending_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ledger_id_val', models.BigIntegerField(blank=True, null=True)),
                ('party_customer_id', models.BigIntegerField(blank=True, null=True)),
                ('party_vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('pay_from_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_from', to='accounting.masterledger')),
                ('pay_to_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_to', to='accounting.masterledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='accounting.transaction')),
            ],
            options={
                'db_table': 'pending_transaction',
            },
        ),
    ]
