# Generated by Django 5.0.14 on 2026-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_transactionallocation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpurchaseduedetails',
            name='advance_references',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalespaymentdetails',
            name='advance_references',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
