# Generated by Django 5.0.14 on 2026-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_voucherpurchaseduedetails_advance_references_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceallocation',
            name='ledger_id_val',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='party_customer_id',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='ledger_id_val',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='party_customer_id',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='ledger_id_val',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='party_customer_id',
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
    ]
