# Generated by Django 5.0.14 on 2026-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_remove_advanceallocation_ledger_id_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='party_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
