# Generated by Django 5.0.14 on 2026-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_advanceallocation_ledger_id_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceallocation',
            name='transaction_details',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='transaction_details',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='transaction_details',
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='details_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='details_original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='details_party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='details_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='details_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='details_original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='details_party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='details_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='details_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='details_original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='details_party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='details_ref_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
