# Generated by Django 5.0.14 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_advanceallocation_transaction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_to_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_to_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='pay_to_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_in_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_in_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='receive_in_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='pay_to_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_in_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_in_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='receive_in_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_to_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_to_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_to_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_in_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_in_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_in_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_to_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_to_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='pay_to_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_from_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_from_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_from_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_in_customer_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_in_ledger_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='receive_in_vendor_id_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
