# Generated by Django 5.0.14 on 2026-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_advanceallocation_pay_from_customer_id_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceallocation',
            name='details_description',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='details_original_date',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='details_party_name',
        ),
        migrations.RemoveField(
            model_name='advanceallocation',
            name='details_ref_no',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='details_description',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='details_original_date',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='details_party_name',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='details_ref_no',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='details_description',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='details_original_date',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='details_party_name',
        ),
        migrations.RemoveField(
            model_name='transactionallocation',
            name='details_ref_no',
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='due_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advanceallocation',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='due_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='due_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionallocation',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
