# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_merge_20260414_0315'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        SET @name_col_exists := (
                            SELECT COUNT(*)
                            FROM information_schema.columns
                            WHERE table_schema = DATABASE()
                              AND table_name = 'master_ledgers'
                              AND column_name = 'name'
                        );
                        SET @copy_name_sql := IF(
                            @name_col_exists > 0,
                            'UPDATE master_ledgers
                             SET ledger_type = name
                             WHERE (ledger_type IS NULL OR TRIM(ledger_type) = '''')
                               AND name IS NOT NULL
                               AND TRIM(name) <> '''';',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @copy_name_sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        SET @idx_exists := (
                            SELECT COUNT(*)
                            FROM information_schema.statistics
                            WHERE table_schema = DATABASE()
                              AND table_name = 'master_ledgers'
                              AND index_name = 'master_ledgers_name_tenant_unique'
                        );
                        SET @drop_idx_sql := IF(
                            @idx_exists > 0,
                            'ALTER TABLE master_ledgers DROP INDEX master_ledgers_name_tenant_unique',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @drop_idx_sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        SET @name_col_exists := (
                            SELECT COUNT(*)
                            FROM information_schema.columns
                            WHERE table_schema = DATABASE()
                              AND table_name = 'master_ledgers'
                              AND column_name = 'name'
                        );
                        SET @drop_name_sql := IF(
                            @name_col_exists > 0,
                            'ALTER TABLE master_ledgers DROP COLUMN name',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @drop_name_sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                    """,
                    reverse_sql="""
                        ALTER TABLE master_ledgers
                        ADD COLUMN name VARCHAR(255) NULL;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        SET @new_idx_exists := (
                            SELECT COUNT(*)
                            FROM information_schema.statistics
                            WHERE table_schema = DATABASE()
                              AND table_name = 'master_ledgers'
                              AND index_name = 'master_ledgers_name_tenant_unique'
                        );
                        SET @dup_exists := (
                            SELECT COUNT(*)
                            FROM (
                                SELECT ledger_type, tenant_id, COUNT(*) AS c
                                FROM master_ledgers
                                GROUP BY ledger_type, tenant_id
                                HAVING COUNT(*) > 1
                            ) t
                        );
                        SET @add_idx_sql := IF(
                            @new_idx_exists = 0 AND @dup_exists = 0,
                            'ALTER TABLE master_ledgers ADD UNIQUE INDEX master_ledgers_name_tenant_unique (ledger_type, tenant_id)',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @add_idx_sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='masterledger',
                    name='name',
                    field=models.CharField(blank=True, db_column='ledger_type', max_length=255, null=True),
                ),
                migrations.RemoveField(
                    model_name='masterledger',
                    name='ledger_type',
                ),
            ],
        ),
    ]
