# Generated by Django 5.0.14 on 2026-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexpense',
            name='voucher_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
