# Generated by Django 5.0.14 on 2026-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance amount for this ledger', max_digits=20),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='opening_balance_type',
            field=models.CharField(blank=True, default='debit', help_text="Opening balance type: 'debit' or 'credit'", max_length=10),
        ),
    ]
