# Generated by Django 5.0.14 on 2026-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_add_voucher_series_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherjournal',
            name='voucher_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
