# Generated by Django 5.0.14 on 2026-04-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_add_opening_balance_to_masterledger'),
        ('accounting', '0044_add_voucher_series_to_journal'),
    ]

    operations = [
    ]
