# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_masterledger_drop_name_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexpense',
            name='expense_rows',
            field=models.JSONField(blank=True, default=list, help_text='Exact expense row payload from frontend'),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherexpense',
            name='total_taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='show_tax',
            field=models.BooleanField(default=False),
        ),
    ]
