# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_expense_header_and_tax_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherexpense',
            name='expense_rows',
        ),
        migrations.AlterField(
            model_name='voucherexpense',
            name='uploaded_files',
            field=models.TextField(blank=True, default=''),
        ),
    ]
