# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_remove_expense_json_and_store_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterledger',
            name='code',
            field=models.CharField(blank=True, db_column='ledger_code', help_text='Auto-generated code based on hierarchy position', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='masterledger',
            unique_together={('tenant_id', 'code'), ('name', 'tenant_id')},
        ),
    ]
