# Generated by Django 5.0.14 on 2026-04-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTempOCR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_hash', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('upload_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('validation_status', models.CharField(default='PENDING', max_length=50)),
                ('vendor_status', models.CharField(default='PENDING', max_length=50)),
                ('matched_by', models.CharField(blank=True, max_length=100, null=True)),
                ('conflict_message', models.TextField(blank=True, null=True)),
                ('vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('voucher_id', models.BigIntegerField(blank=True, null=True)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, max_length=64, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('selected_by', models.CharField(default='FALLBACK', max_length=50)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('version_rank', models.IntegerField(default=99)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invoice_ocr_temp',
                'managed': False,
            },
        ),
    ]
