# Generated by Django 5.0.14 on 2026-05-04 06:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0002_ocrjob_ocrtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ocrjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocrtask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['tenant_id', 'status'], name='ocr_jobs_tenant__8006e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['created_at'], name='ocr_jobs_created_d484ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrtask',
            index=models.Index(fields=['job', 'status'], name='ocr_tasks_job_id_89256b_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrtask',
            index=models.Index(fields=['file_hash'], name='ocr_tasks_file_ha_dfee91_idx'),
        ),
    ]
