# Generated by Django 5.0.14 on 2026-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0003_ocrtask_file_url_ocrtask_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProcessingLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=255)),
                ('task_id', models.UUIDField()),
                ('result_id', models.BigIntegerField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ocr_processing_locks',
                'indexes': [models.Index(fields=['file_hash', 'tenant_id'], name='ocr_process_file_ha_0d2f75_idx')],
                'unique_together': {('file_hash', 'tenant_id')},
            },
        ),
    ]
