# Generated by Django 5.0.14 on 2026-05-09 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0004_ocrprocessinglock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('snapshot_json', models.JSONField()),
                ('invoice_count', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'finalized_snapshots',
                'indexes': [models.Index(fields=['session_id', 'tenant_id'], name='finalized_s_session_be14da_idx')],
            },
        ),
    ]
