# Generated by Django 5.0.14 on 2026-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0005_finalizedsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFinalizationState',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_pages_expected', models.IntegerField(default=0)),
                ('total_pages_completed', models.IntegerField(default=0)),
                ('snapshot_created', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_finalization_states',
            },
        ),
    ]
