# Generated by Django 5.0.14 on 2026-05-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0006_sessionfinalizationstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetempocr',
            options={'managed': True},
        ),
    ]
