# Generated by Django 5.0.14 on 2026-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0007_alter_invoicetempocr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetempocr',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=50),
        ),
    ]
