# Generated by Django 5.0.14 on 2026-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0008_alter_invoicetempocr_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetempocr',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='InvoicePageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField(db_index=True)),
                ('page_number', models.IntegerField()),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('canonical_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_page_results',
                'indexes': [models.Index(fields=['record_id', 'page_number'], name='invoice_pag_record__464fee_idx'), models.Index(fields=['session_id'], name='invoice_pag_session_0984f6_idx')],
                'unique_together': {('record_id', 'page_number')},
            },
        ),
    ]
