# Generated by Django 5.0.14 on 2026-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0009_alter_invoicetempocr_options_invoicepageresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='failed_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='processed_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
