# Generated by Django 5.0.14 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0010_ocrjob_failed_pages_ocrjob_processed_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedsnapshot',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedsnapshot',
            name='snapshot_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
