# Generated by Django 5.0.14 on 2026-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0012_poisonpdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('key_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Inference Cache',
                'verbose_name_plural': 'AI Inference Caches',
                'db_table': 'ai_inference_cache',
            },
        ),
    ]
