# Generated by Django 5.0.14 on 2026-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0013_aicache'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepageresult',
            name='counted_in_barrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicepageresult',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
