# Generated by Django 5.0.14 on 2026-05-16 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0014_add_barrier_idempotency_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoisonDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('record_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('worker_role', models.CharField(max_length=50)),
                ('queue_name', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('error_trace', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poison Document',
                'verbose_name_plural': 'Poison Documents',
                'db_table': 'poison_documents',
            },
        ),
    ]
