# Generated by Django 5.0.14 on 2026-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0015_poisondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('worker_node', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipeline_events',
                'indexes': [models.Index(fields=['record_id', 'created_at'], name='pipeline_ev_record__2c175a_idx'), models.Index(fields=['session_id', 'status'], name='pipeline_ev_session_94faa3_idx')],
            },
        ),
    ]
