# Generated by Django 5.0.14 on 2026-05-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0016_pipelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineevent',
            name='causation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='event_sequence',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='parent_event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='workflow_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='workflow_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='pipelineevent',
            index=models.Index(fields=['workflow_id', 'workflow_version'], name='pipeline_ev_workflo_f54505_idx'),
        ),
    ]
