# Generated by Django 5.0.14 on 2026-05-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0017_pipelineevent_causation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipelineevent',
            unique_together={('workflow_id', 'event_sequence')},
        ),
    ]
