# Generated by Django 5.0.14 on 2026-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0018_alter_pipelineevent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSequence',
            fields=[
                ('workflow_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('current_sequence', models.BigIntegerField(default=0)),
                ('current_version', models.BigIntegerField(default=0)),
                ('last_event_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_sequences',
            },
        ),
    ]
