# Generated by Django 5.0.14 on 2026-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0019_workflowsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineevent',
            name='event_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='event_schema_version',
            field=models.IntegerField(default=1),
        ),
    ]
