# Generated by Django 5.0.14 on 2026-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0020_pipelineevent_event_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='ai_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='expected_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='export_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='exported_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='ingestion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='materialization_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='materialized_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='snapshot_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='status',
            field=models.CharField(default='UPLOADED', max_length=50),
        ),
    ]
