# Generated by Django 5.0.14 on 2026-06-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0021_sessionfinalizationstate_ai_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='upload_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
