# Generated by Django 5.0.14 on 2026-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0022_ocrjob_is_cancelled_ocrjob_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='assembly_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='continuation_merge_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='hydration_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='terminal_consistency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionfinalizationstate',
            name='validation_complete',
            field=models.BooleanField(default=False),
        ),
    ]
