# Generated by Django 5.0.14 on 2026-06-16 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_pipeline', '0023_sessionfinalizationstate_assembly_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rescan_type', models.CharField(max_length=50)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('cost_impact', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('invoice_temp_ocr', models.ForeignKey(db_column='invoice_temp_ocr_id', on_delete=django.db.models.deletion.CASCADE, related_name='rescan_history', to='ocr_pipeline.invoicetempocr')),
            ],
            options={
                'verbose_name': 'Rescan History',
                'verbose_name_plural': 'Rescan Histories',
                'db_table': 'rescan_history',
            },
        ),
        migrations.CreateModel(
            name='AIUsageAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_temp_ocr', models.ForeignKey(db_column='invoice_temp_ocr_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to='ocr_pipeline.invoicetempocr')),
                ('rescan_history', models.ForeignKey(blank=True, db_column='rescan_history_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='ocr_pipeline.rescanhistory')),
            ],
            options={
                'verbose_name': 'AI Usage Accounting',
                'verbose_name_plural': 'AI Usage Accountings',
                'db_table': 'ai_usage_accounting',
            },
        ),
    ]
