# Generated by Django 5.0.14 on 2026-04-11 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_count', models.IntegerField(default=1)),
                ('processing_time_seconds', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extraction_performance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('tan', models.CharField(blank=True, max_length=10, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_year_start', models.DateField(blank=True, null=True)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_numbering', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(db_column='master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.masteruser')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company')),
                ('master', models.ForeignKey(db_column='master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='company.masteruser')),
            ],
            options={
                'db_table': 'tenants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('used_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
            options={
                'db_table': 'ai_usage',
                'managed': True,
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
