# Generated by Django 5.0.14 on 2026-04-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_remove_user_company_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aiusage',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='master',
        ),
        migrations.RemoveField(
            model_name='company',
            name='master',
        ),
        migrations.DeleteModel(
            name='ExtractionPerformance',
        ),
        migrations.DeleteModel(
            name='AIUsage',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='MasterUser',
        ),
    ]
