class ValidationEnums:
    VENDOR_STATUS_EXISTING = 'VENDOR_STATUS_EXISTING'
    VENDOR_STATUS_CREATE = 'VENDOR_STATUS_CREATE'
    
    VOUCHER_STATUS_EXISTING = 'VOUCHER_STATUS_EXISTING'
    VOUCHER_STATUS_NEW = 'VOUCHER_STATUS_NEW'
    
    ITEM_STATUS_EXISTING = 'ITEM_STATUS_EXISTING'
    ITEM_STATUS_CREATE = 'ITEM_STATUS_CREATE'

UI_STATUS_MAP = {
    ValidationEnums.VENDOR_STATUS_EXISTING: 'ALREADY EXIST',
    ValidationEnums.VENDOR_STATUS_CREATE: 'CREATE VENDOR',
    ValidationEnums.VOUCHER_STATUS_EXISTING: 'ALREADY EXIST',
    ValidationEnums.VOUCHER_STATUS_NEW: 'NEED_TO_SAVE',
    ValidationEnums.ITEM_STATUS_EXISTING: 'ALREADY EXIST',
    ValidationEnums.ITEM_STATUS_CREATE: 'CREATE ITEM',
}
