# Generated by Django 5.0.14 on 2026-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('service_code', models.CharField(db_index=True, help_text='Unique service code identifier', max_length=50, unique=True)),
                ('service_name', models.CharField(help_text='Service name', max_length=255)),
                ('service_group', models.CharField(db_index=True, help_text='Service group/category', max_length=100)),
                ('sac_code', models.CharField(help_text='SAC (Services Accounting Code)', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, help_text='GST rate percentage', max_digits=5)),
                ('expense_ledger', models.CharField(help_text='Expense ledger account', max_length=255)),
                ('uom', models.CharField(blank=True, help_text='Unit of Measurement', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status of the service')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service_list',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_code'], name='service_lis_service_43ab40_idx'), models.Index(fields=['service_group'], name='service_lis_service_8ffa00_idx'), models.Index(fields=['is_active'], name='service_lis_is_acti_da762e_idx'), models.Index(fields=['created_at'], name='service_lis_created_fc7c06_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(help_text='Top-level category', max_length=100)),
                ('group', models.CharField(blank=True, default='', help_text='Group under category (optional)', max_length=100)),
                ('subgroup', models.CharField(blank=True, default='', help_text='Subgroup under group (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_group',
                'ordering': ['category', 'group', 'subgroup'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='service_gro_tenant__1579a4_idx'), models.Index(fields=['category'], name='service_gro_categor_ac5750_idx')],
                'unique_together': {('tenant_id', 'category', 'group', 'subgroup')},
            },
        ),
    ]
