# Generated by Django 5.0.14 on 2026-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(help_text='Top-level category', max_length=100)),
                ('group', models.CharField(blank=True, help_text='Group under category (optional)', max_length=100, null=True)),
                ('subgroup', models.CharField(blank=True, help_text='Subgroup under group (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_group',
                'ordering': ['category', 'group', 'subgroup'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='service_gro_tenant__1579a4_idx'), models.Index(fields=['category'], name='service_gro_categor_ac5750_idx')],
                'unique_together': {('tenant_id', 'category', 'group', 'subgroup')},
            },
        ),
    ]
