# Generated by Django 5.0.14 on 2026-04-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
    ]
