# Generated by Django 5.0.14 on 2026-04-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicegroup_tenant_id_servicegroup_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='tenant',
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
