# Generated by Django 5.0.14 on 2026-04-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_amounttransaction_vendor_journalentry_vendor_and_more'),
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermastercustomerbasicdetails',
            name='ledger',
            field=models.ForeignKey(blank=True, db_column='ledger_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customers_basic', to='accounting.masterledger'),
        ),
    ]
