# Generated by Django 5.2.9 on 2026-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermastercustomertermscondition',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
