# Generated by Django 5.2.9 on 2026-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMastersSalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('series_name', models.CharField(max_length=100)),
                ('customer_category', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(default='SO/', max_length=20)),
                ('suffix', models.CharField(default='/24-25', max_length=20)),
                ('required_digits', models.IntegerField(default=4)),
                ('current_number', models.IntegerField(default=0)),
                ('auto_year', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_masters_salesorder',
                'indexes': [models.Index(fields=['tenant_id', 'is_deleted'], name='customer_ma_tenant__64d142_idx'), models.Index(fields=['tenant_id', 'customer_category'], name='customer_ma_tenant__e26271_idx')],
                'unique_together': {('tenant_id', 'series_name')},
            },
        ),
    ]
