# Generated by Django 5.0.14 on 2026-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='ledger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
