# Generated by Django 5.2.9 on 2026-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransactionsalesquotationspecificitem',
            name='specific_quote',
        ),
        migrations.AddField(
            model_name='customertransactionsalesquotationgeneral',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='customertransactionsalesquotationspecific',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesQuotationGeneralItem',
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesQuotationSpecificItem',
        ),
    ]
