# Generated by Django 5.0.14 on 2026-04-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_customertransaction_is_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransaction',
            name='is_advance',
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='ledger_name',
        ),
        migrations.RemoveField(
            model_name='customertransaction',
            name='reference_type',
        ),
    ]
