# Generated by Django 5.0.14 on 2026-04-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_customermastercustomerbasicdetails_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationGeneralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('uom', models.CharField(max_length=50)),
                ('effective_rate', models.DecimalField(decimal_places=2, help_text='Rate specified in quotation', max_digits=15)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rel', to='customerportal.customertransactionsalesquotationgeneral')),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_general_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationSpecificItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('uom', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rel', to='customerportal.customertransactionsalesquotationspecific')),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_specific_items',
            },
        ),
    ]
