# Generated by Django 5.0.14 on 2026-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_customermasterssalesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransactionsalesorderbasicdetails',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customertransactionsalesorderdeliveryterms',
            name='third_party_address',
            field=models.JSONField(blank=True, help_text='Third Party Delivery Address Details', null=True),
        ),
        migrations.AddField(
            model_name='customertransactionsalesorderitemdetails',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST Rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='customertransactionsalesorderitemdetails',
            name='uom',
            field=models.CharField(blank=True, help_text='Unit of Measure', max_length=50, null=True),
        ),
    ]
