# Generated by Django 5.0.14 on 2026-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0003_remove_customertransaction_is_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customermasterlongtermcontractproductservice',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermasterlongtermcontractproductservice',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermasterlongtermcontractproductservice',
            name='qty_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermasterlongtermcontractproductservice',
            name='qty_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesorderitemdetails',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST Amount', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesorderitemdetails',
            name='net_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net Value (Taxable + GST)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesorderitemdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesorderitemdetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesorderitemdetails',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxable Value (Qty * Price)', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationgeneralitem',
            name='effective_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate specified in quotation', max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationspecificitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationspecificitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationspecificitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationspecificitem',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='customertransactionsalesquotationspecificitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
