# Generated by Django 5.0.14 on 2026-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0003_customertransactionsalesquotationgeneralitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermastercustomertds',
            name='tcs_section',
            field=models.CharField(blank=True, help_text='TCS Section', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customermastercustomertds',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section', max_length=500, null=True),
        ),
    ]
