/**
 * ============================================================================
 * TYPE DEFINITIONS (types.ts)
 * ============================================================================
 * This file contains ALL TypeScript type definitions for the application.
 * Types define the "shape" of data - what fields exist and their data types.
 * 
 * WHY TYPES MATTER:
 * - Catch bugs at compile-time (before running the code)
 * - Enable autocomplete in your IDE
 * - Document what data looks like
 * - Make refactoring safer
 * 
 * MAIN CATEGORIES:
 * 1. UI Types (Page navigation)
 * 2. Company & Settings
 * 3. Chart of Accounts (Ledgers, Groups)
 * 4. Inventory (Stock Items, Units, Groups)
 * 5. Vouchers (Transactions)
 * 6. AI Features (Invoice extraction, AI Agent)

 * 
 * FOR NEW DEVELOPERS:
 * - Always import types when working with data
 * - Use TypeScript's type checking to avoid errors
 * - Add new types here when adding new features
 */

// ============================================================================
// UI & NAVIGATION TYPES
// ============================================================================

/**
 * Page - Defines all possible pages/sections in the application
 * Used for routing and navigation
 */
export type Page = 'Dashboard' | 'Masters' | 'Inventory' | 'Vouchers' | 'Reports' | 'Settings' | 'MassUploadResult' | 'Vendor Portal' | 'Customer Portal' | 'Payroll' | 'Service' | 'Users & Roles' | 'GST';

// ============================================================================
// COMPANY & SETTINGS TYPES
// ============================================================================

/**
 * CompanyDetails - Stores company information and settings
 * This is saved in the backend and loaded on login
 */
export interface CompanyDetails {
  name: string;              // Company name
  address: string;           // Registered address
  gstin: string;             // GST Identification Number
  state: string;             // State for GST purposes
  logo?: string;             // Company logo URL (optional)
  tax_id?: string;           // Tax ID (optional)
  email?: string;            // Contact email (optional)
  phone?: string;            // Contact phone (optional)
  website?: string;          // Company website (optional)
  pan?: string;              // PAN number (optional)
  cin?: string;              // Corporate Identification Number (optional)

  // Voucher numbering configuration - auto-generates invoice numbers
  voucherNumbering?: {
    [voucherType: string]: {
      autoIncrement: boolean;  // Enable auto-increment
      prefix: string;          // e.g., "INV-"
      nextNumber: number;      // Next number to use
      width: number;           // Padding width (e.g., 4 = "0001")
      suffix: string;          // e.g., "/24-25"
    };
  };

}

// ============================================================================
// CHART OF ACCOUNTS TYPES
// ============================================================================

/**
 * LedgerGroupMaster - Hierarchical grouping of ledgers
 * Example: "Bank Accounts" under "Current Assets"
 */
export interface LedgerGroupMaster {
  id?: number;       // Unique identifier (auto-generated by backend)
  name: string;      // Group name (e.g., "Bank Accounts")
  under: string;     // Parent group name (e.g., "Current Assets")
}

/**
 * LedgerGroup - Predefined ledger group types
 * These are the standard accounting groups
 */
export type LedgerGroup = 'Sundry Debtors' | 'Sundry Creditors' | 'Bank Accounts' | 'Cash-in-Hand' | 'Duties & Taxes' | 'Direct Expenses' | 'Indirect Incomes' | 'Sales Accounts' | 'Purchase Accounts' | 'Capital Account' | 'Current Assets' | 'Current Liabilities' | 'Fixed Assets' | 'Investments' | 'Loans (Liability)' | 'Misc. Expenses (ASSET)' | 'Branch / Divisions' | 'Reserves & Surplus' | 'Secured Loans' | 'Unsecured Loans' | 'Suspense A/c' | 'Bank OD A/c';

/**
 * Ledger - Individual account in the chart of accounts
 * Examples: "HDFC Bank", "Cash", "Sales - Product A", "ACME Corp (Customer)"
 * 
 * IMPORTANT: Ledgers are the foundation of double-entry accounting
 * Every transaction involves at least 2 ledgers (debit and credit)
 */
export interface Ledger {
  id?: number;                    // Unique identifier
  name: string;                   // Ledger name (e.g., "HDFC Bank")
  group: string;                  // Ledger group (e.g., "Bank Accounts")

  // Hierarchy fields (required by backend for classification)
  category?: string;              // Top-level category
  sub_group_1?: string;           // First sub-group
  sub_group_2?: string;           // Second sub-group
  sub_group_3?: string;           // Third sub-group
  ledger_type?: string;           // Type of ledger

  // Parent ledger for nested custom ledgers
  parent_ledger_id?: number;      // Reference to parent ledger

  // Auto-generated code based on hierarchy
  ledger_code?: string;           // Unique code (e.g., "BA-001")

  // GST-related fields (for parties/vendors/customers)
  gstin?: string;                 // GST Number
  registrationType?: 'Registered' | 'Unregistered' | 'Composition';
  state?: string;                 // State for GST purposes

  // Loan-specific fields
  loanAccountNumber?: string;
  panGstin?: string;
  lenderName?: string;
  loanAmount?: string;
  interestType?: string;
  interestRate?: string;
  loanStartDate?: string;
  loanEndDate?: string;
  securityType?: string;          // 'Collateral' or 'Guarantee'
  tenure?: string;                // Backward compatibility - tenure in months
  tenureOption?: string;          // 'dates' or 'tenure'
  tenureDays?: string;
  tenureMonths?: string;
  tenureYears?: string;

  // Bank account-specific fields
  bankAccountNumber?: string;
  gstinPan?: string;
  enableBankReconciliation?: boolean;
  bankName?: string;
  ifscCode?: string;
  branch?: string;
  bankingCurrency?: string;
  referenceWiseTracking?: string;
  creditPeriod?: string;

  // Asset-specific fields
  isDepreciationPerIncomeTax?: string;
  depreciationPercentage?: string;
  isAmortizationPerIncomeTax?: string;
  amortizationPercentage?: string;

  // Investment-specific fields
  companyCIN?: string;
  dividendRate?: string;
  equityInstrumentsCIN?: string;
  debentureBondCIN?: string;
  debentureBondInterestRate?: string;
  debentureBondMaturityDate?: string;

  // Inventory-specific fields
  inventoryType?: string;
  inventoryValuationMethod?: string;

  // Cash-specific fields
  cashLocation?: string;

  // Dynamic questions/answers for ledger creation wizard
  question_answers?: Record<number, any>;
}

// ============================================================================
// INVENTORY TYPES
// ============================================================================

/**
 * Unit - Unit of measurement for stock items
 * Examples: Pcs, Kg, Litre, Box, Dozen
 */
export interface Unit {
  id?: number;       // Unique identifier
  name: string;      // Unit name (e.g., "Kg", "Pcs")
}

/**
 * StockGroup - Category/group for stock items
 * Examples: "Raw Materials", "Finished Goods", "Electronics"
 */
export interface StockGroup {
  id?: number;       // Unique identifier
  name: string;      // Group name
}

/**
 * StockItem - Individual product/inventory item
 * Examples: "iPhone 15", "Steel Rod 10mm", "Laptop Dell XPS"
 */
export interface StockItem {
  id?: number;       // Unique identifier
  name: string;      // Item name
  group: string;     // Stock group name
  unit: string;      // Unit of measurement
  hsn?: string;      // HSN/SAC code for GST
  gstRate?: number;  // GST rate (e.g., 18 for 18%)
  quantity?: number; // Current stock quantity
}

export interface VoucherItem {
  name: string;
  qty: number;
  rate: number;
  taxableAmount: number;
  cgstAmount: number;
  sgstAmount: number;
  igstAmount: number;
  totalAmount: number;
}

export type VoucherType = 'Purchase' | 'Sales' | 'Payment' | 'Receipt' | 'Contra' | 'Journal' | 'Expenses';

export interface BaseVoucher {
  id: string;
  type: VoucherType;
  date: string;
  narration?: string;
  image?: string;
}

export interface SalesPurchaseVoucher extends BaseVoucher {
  type: 'Purchase' | 'Sales';
  isInterState: boolean;
  invoiceNo: string;
  dueDate?: string;
  party: string;
  items: VoucherItem[];
  totalTaxableAmount: number;
  totalCgst: number;
  totalSgst: number;
  totalIgst: number;
  total: number;
}

export interface PaymentReceiptVoucher extends BaseVoucher {
  type: 'Payment' | 'Receipt';
  account: string; // Bank or Cash ledger
  party: string;
  amount: number;
}

export interface ContraVoucher extends BaseVoucher {
  type: 'Contra';
  fromAccount: string; // From Cash/Bank
  toAccount: string;   // To Cash/Bank
  amount: number;
}

export interface JournalEntry {
  ledger: string;
  note: string;
  refNo: string;
  debit: number;
  credit: number;
}
export interface JournalVoucher extends BaseVoucher {
  type: 'Journal';
  entries: JournalEntry[];
  totalDebit: number;
  totalCredit: number;
};

export interface ExpensesVoucher extends BaseVoucher {
  type: 'Expenses';
  account: string; // Bank or Cash ledger (Paid From)
  party: string;   // Expense category ledger
  amount: number;
}


export type Voucher = SalesPurchaseVoucher | PaymentReceiptVoucher | ContraVoucher | JournalVoucher | ExpensesVoucher;

// Voucher Masters
export interface VoucherTypeMaster {
  id: number;
  name: string;
  description?: string;
  tenantId: string;
  createdAt: string;
  updatedAt: string;
}

export interface VoucherNumbering {
  enableAuto: boolean;
  prefix: string;
  suffix: string;
  nextNumber: number;
  padding: number;
  preview?: string;
}

// For AI data extraction
export interface ExtractedLineItem {
  itemDescription: string;
  hsnCode: string;
  quantity: number;
  rate: number;
  amount: number;
}

export interface ExtractedInvoiceData {
  sellerName: string;
  invoiceNumber: string;
  invoiceDate: string; // YYYY-MM-DD
  dueDate?: string; // YYYY-MM-DD
  subtotal: number;
  cgstAmount: number;
  sgstAmount: number;
  igstAmount: number;
  totalAmount: number;
  lineItems: ExtractedLineItem[];
}

// For AI Agent
export interface AgentMessage {
  role: 'user' | 'model';
  text: string;
  sources?: { uri: string; title: string; }[];
}

// For Mass Upload feature
export type MassUploadStatus = 'pending' | 'processing' | 'success' | 'error';

export interface MassUploadFile {
  id: string;
  file: File;
  status: MassUploadStatus;
  extractedData?: ExtractedInvoiceData;
  error?: string;
}

// For User Data
export interface User {
  id: number;
  username: string;
  name: string;
  email?: string;
  is_active: boolean;
  tenantId: string;
}

// For Module-Submodule UI
export interface Submodule {
  id: number;
  name: string;
  description?: string;
  user_table?: number;
  created_at?: string;
}

export interface UserTable {
  id: number;
  name: string;
  description?: string;
  submodules: Submodule[];
  created_at?: string;
}

// ============================================================================
// RBAC (Role-Based Access Control) TYPES
// ============================================================================

/**
 * TabPermissions - Permissions for individual tabs within a page
 * Key: tab name, Value: boolean (true = has access)
 */
export interface TabPermissions {
  [tabName: string]: boolean;
}

/**
 * PagePermissions - Permissions for a page and its tabs
 */
export interface PagePermissions {
  view: boolean;           // Can view the page
  tabs?: TabPermissions;   // Optional tab-level permissions
}

/**
 * Permissions - Complete permission structure for all pages
 * Key: page name, Value: PagePermissions
 */
export interface Permissions {
  [pageName: string]: PagePermissions;
}

/**
 * Role - User role with hierarchical permissions
 * Examples: Admin, Accountant, Sales Manager, Inventory Manager
 */
export interface Role {
  id?: number;
  name: string;
  description?: string;
  permissions: Permissions;
  is_active?: boolean;
  tenant_id?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * UserRole - Assignment of a role to a user
 */
export interface UserRole {
  id?: number;
  user_id: number;
  role_id: number;
  role_name?: string;
  role_description?: string;
  user_username?: string;
  assigned_at?: string;
  assigned_by?: number;
  tenant_id?: string;
}

/**
 * UserWithRoles - User with their assigned roles and combined permissions
 */
export interface UserWithRoles {
  id: number;
  username: string;
  email?: string;
  company_name?: string;
  phone?: string;
  is_active: boolean;
  tenant_id?: string;
  roles: {
    id: number;
    name: string;
    description?: string;
    assigned_at: string;
  }[];
  permissions: Permissions;
  created_at?: string;
  updated_at?: string;
}

/**
 * CreateUserWithRole - Data for creating a new user with role assignment
 */
export interface CreateUserWithRole {
  username: string;
  email?: string;
  password: string;
  phone?: string;
  role_ids?: number[];
}

/**
 * PermissionLog - Audit trail for permission changes
 */
export interface PermissionLog {
  id: number;
  role_id: number;
  role_name: string;
  changed_by_id?: number;
  changed_by_username?: string;
  action: 'created' | 'updated' | 'deleted';
  old_permissions?: Permissions;
  new_permissions?: Permissions;
  change_summary?: string;
  created_at: string;
  tenant_id: string;
}

/**
 * PermissionsStructure - Available pages and tabs for permission configuration
 * Used to build the permission tree UI
 */
export interface PermissionsStructure {
  [pageName: string]: {
    tabs: string[];
  };
}
