# Generated by Django 5.0.14 on 2026-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_session_id', models.CharField(db_index=True, max_length=255)),
                ('source_scan_row_id', models.BigIntegerField(db_index=True)),
                ('source_document_hash', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=512, null=True)),
                ('vendor_gstin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor_status', models.CharField(default='PENDING', max_length=50)),
                ('voucher_status', models.CharField(default='PENDING', max_length=50)),
                ('item_status', models.CharField(default='PENDING', max_length=50)),
                ('pending_purchase_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=50)),
                ('extraction_payload', models.JSONField(blank=True, null=True)),
                ('review_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_purchase_queue',
            },
        ),
        migrations.AddConstraint(
            model_name='pendingpurchase',
            constraint=models.UniqueConstraint(fields=('source_scan_row_id',), name='unique_source_scan_row'),
        ),
        migrations.AddConstraint(
            model_name='pendingpurchase',
            constraint=models.UniqueConstraint(fields=('source_document_hash',), name='unique_source_document_hash'),
        ),
    ]
