# Generated by Django 5.0.14 on 2026-06-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pending_purchases', '0001_initial'),
    ]

    operations = [
    ]
