# Generated by Django 5.0.14 on 2026-04-20 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('executed_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gst_reconciliation_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='GSTR2BInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('upload_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('gstin', models.CharField(max_length=15)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fingerprint', models.CharField(help_text='Hash of GSTIN + Invoice No + Date + Value', max_length=64, unique=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_reconciliation_gstr2b_invoices',
            },
        ),
        migrations.CreateModel(
            name='GSTR3BReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('period_month', models.CharField(max_length=20)),
                ('period_year', models.CharField(max_length=10)),
                ('output_tax_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_tax_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_tax_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_tax_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_tax_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('input_tax_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'gst_reconciliation_gstr3b_reports',
            },
        ),
        migrations.CreateModel(
            name='ITCSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('period_month', models.CharField(max_length=20)),
                ('period_year', models.CharField(max_length=10)),
                ('total_itc_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_itc_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_itc_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('eligible_itc_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('eligible_itc_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('eligible_itc_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('blocked_itc_igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('matching_criteria_used', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_reconciliation_itc_summaries',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_voucher_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('matching_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('EXACT', 'Exact Match'), ('PARTIAL', 'Partial Match'), ('MISMATCH', 'Mismatch'), ('MISSING_2B', 'Missing in GSTR-2B'), ('MISSING_BOOKS', 'Missing in Books')], max_length=20)),
                ('matching_details', models.JSONField(blank=True, null=True)),
                ('invoice_2b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gst_reconciliation.gstr2binvoice')),
            ],
            options={
                'db_table': 'gst_reconciliation_results',
            },
        ),
    ]
