# Generated by Django 5.0.14 on 2026-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_type', models.CharField(choices=[('RECO', 'Reconciliation'), ('ITC', 'ITC Computation'), ('3B', 'GSTR-3B Generation')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_reconciliation_job_status',
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('period_month', models.CharField(max_length=20)),
                ('period_year', models.CharField(max_length=10)),
                ('check_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('INFO', 'Info')], default='WARNING', max_length=10)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_reconciliation_validation_results',
            },
        ),
    ]
