# Generated by Django 5.0.14 on 2026-04-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(db_index=True, help_text='UUID grouping all rows from one upload', max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, default='')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inferred_type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt')], default='payment', max_length=10)),
                ('ledger_id', models.BigIntegerField(blank=True, help_text='ID from accounting.MasterLedger', null=True)),
                ('ledger_name', models.CharField(blank=True, default='', help_text='Denormalized name for quick display', max_length=255)),
                ('bank_ledger_id', models.BigIntegerField(blank=True, null=True)),
                ('bank_ledger_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('mapped', 'Mapped'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('voucher_id', models.BigIntegerField(blank=True, help_text='ID of created voucher after posting', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Original Gemini row dict, unmodified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Statement Staging Row',
                'verbose_name_plural': 'Bank Statement Staging Rows',
                'db_table': 'bank_statement_temp',
                'ordering': ['date', 'id'],
            },
        ),
    ]
