# Generated by Django 5.0.14 on 2026-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtemp',
            name='allocation_data',
            field=models.JSONField(blank=True, help_text='Manual allocation: {pendingTransactions: [], advanceAmount: X, ...}', null=True),
        ),
        migrations.AddField(
            model_name='bankstatementtemp',
            name='category',
            field=models.CharField(blank=True, help_text='vendor | customer | ledger', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementtemp',
            name='party_id',
            field=models.BigIntegerField(blank=True, help_text='Portal ID (Vendor ID or Customer ID)', null=True),
        ),
    ]
