# Generated by Django 5.0.14 on 2026-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0002_bankstatementtemp_allocation_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtemp',
            name='voucher_number',
            field=models.CharField(blank=True, default='', help_text='Number of created voucher after posting', max_length=64),
        ),
    ]
