# Generated by Django 5.0.14 on 2026-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0003_bankstatementtemp_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='voucher_number',
            field=models.CharField(blank=True, help_text='Bank reference number / Cheque number', max_length=64, null=True),
        ),
    ]
