# Generated by Django 5.0.14 on 2026-04-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0004_alter_bankstatementtemp_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
