# Generated by Django 5.0.14 on 2026-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0005_alter_bankstatementtemp_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtemp',
            name='reference_no',
            field=models.CharField(blank=True, help_text='Bank reference number / Cheque number / UPI Ref', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='voucher_number',
            field=models.CharField(blank=True, help_text='INTERNAL voucher number (if applicable)', max_length=64, null=True),
        ),
    ]
