# Generated by Django 5.0.14 on 2026-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0006_bankstatementtemp_reference_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatementtemp',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='bankstatementtemp',
            name='ref_no',
            field=models.CharField(blank=True, help_text='Bank reference number / Cheque number', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='voucher_number',
            field=models.CharField(blank=True, help_text='Internal Voucher number', max_length=64, null=True),
        ),
    ]
