# Generated by Django 5.0.14 on 2026-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0007_remove_bankstatementtemp_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtemp',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Closing balance after this transaction', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementtemp',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Raw OCR text line(s) for this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('mapped', 'Mapped'), ('posted', 'Posted'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='draft', max_length=12),
        ),
    ]
