# Generated by Django 5.0.14 on 2026-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0008_bankstatementtemp_balance_bankstatementtemp_raw_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementStagingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_data', models.JSONField(help_text='Full extracted JSON from Gemini')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bank_statement_temp',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelTable(
            name='bankstatementtemp',
            table='bank_statement_temp_rows',
        ),
    ]
