# Generated by Django 5.0.14 on 2026-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0009_bankstatementstagingfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementstagingfile',
            name='file_hash',
            field=models.CharField(blank=True, help_text='Optional hash for deduplication', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementstagingfile',
            name='account_id',
            field=models.BigIntegerField(blank=True, help_text='Associated bank ledger ID', null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementstagingfile',
            name='expires_at',
            field=models.DateTimeField(help_text='Timestamp for auto-cleanup'),
        ),
    ]
