# Generated by Django 5.0.14 on 2026-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0010_bankstatementstagingfile_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementstagingfile',
            name='session_id',
            field=models.CharField(blank=True, help_text='Links to the active processing session', max_length=64, null=True),
        ),
    ]
