# Generated by Django 5.0.14 on 2026-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0011_bankstatementstagingfile_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtemp',
            name='posting_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
