# Generated by Django 5.0.14 on 2026-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_upload', '0012_bankstatementtemp_posting_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementstagingfile',
            name='transaction_data',
            field=models.JSONField(help_text='Full extracted JSON from AI'),
        ),
        migrations.AlterField(
            model_name='bankstatementtemp',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Original AI row dict, unmodified', null=True),
        ),
    ]
