# Generated by Django 5.0.14 on 2026-04-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='dispatch_from',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='dispatch_time',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='goods_to_location',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='lr_gr_consignment',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='vehicle_no',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_from',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_time',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='lr_gr_consignment',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='inventoryoperationconsumption',
            name='consumption_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationconsumption',
            name='expense_ledger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationconsumption',
            name='fixed_asset_ledger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationconsumption',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationinterunit',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationjobwork',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='reasons_for_return',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymastergrn',
            name='required_digits',
            field=models.PositiveSmallIntegerField(default=4, help_text='Required Digits'),
        ),
        migrations.AlterField(
            model_name='inventoryoperationoutward',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryoperationoutward',
            name='total_boxes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
