# Generated by Django 5.2.9 on 2026-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='delivery_challan',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='eway_bill_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
