# Generated by Django 5.0.14 on 2026-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='dispatch_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='dispatch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='lr_gr_consignment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
