# Generated by Django 5.0.14 on 2026-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS `inventory_operation_grn`;",
            reverse_sql="-- Cannot reverse this migration - table schema was not preserved",
        ),
    ]
