# Generated by Django 5.2.9 on 2026-02-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryoperationoutward_delivery_challan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_from',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='dispatch_time',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='lr_gr_consignment',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='vehicle_no',
        ),
    ]
