# Generated by Django 5.0.14 on 2026-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryoperationconsumption_delivery_challan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymastercategory',
            options={'ordering': ['category', 'group', 'subgroup', 'sub_subgroup']},
        ),
        migrations.AlterUniqueTogether(
            name='inventorymastercategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='dispatch_from',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='dispatch_time',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='lr_gr_consignment',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='inventorymastercategory',
            name='sub_subgroup',
            field=models.CharField(blank=True, default='', help_text='Sub-subgroup under subgroup (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='issue_slip_series',
            field=models.CharField(blank=True, help_text='Issue Slip Series name for production', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventorymastercategory',
            unique_together={('tenant_id', 'category', 'group', 'subgroup', 'sub_subgroup')},
        ),
    ]
