# Generated by Django 6.0 on 2026-02-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_old_grn_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryOperationGRN',
        ),
    ]
