# Generated by Django 5.0.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryoperationnewgrn_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant_id', 'item_code', 'hsn_code'], name='inventory_m_tenant__feb7a0_idx'),
        ),
    ]
