# Generated by Django 5.0.14 on 2026-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymastercategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperationjobwork',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationjobwork',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryoperationjobwork',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationlocationchange',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='secondary_ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='dispatch_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='dispatch_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='dispatch_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='lr_gr_consignment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
