# Generated by Django 5.2.9 on 2026-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryoperationoutward_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='dispatch_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='dispatch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='lr_gr_consignment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
