# Generated by Django 5.0.14 on 2026-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryoperationconsumption',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationinterunit',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationinterunit',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationinterunit',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationjobwork',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationjobwork',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationjobwork',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationlocationchange',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationlocationchange',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationlocationchange',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationnewgrn',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutward',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproduction',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationscrap',
            name='delivery_challan',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationscrap',
            name='eway_bill_details',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationscrap',
            name='items',
        ),
        migrations.CreateModel(
            name='InventoryOperationEWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('operation_type', models.CharField(choices=[('jobwork', 'Job Work'), ('interunit', 'Inter Unit'), ('location_change', 'Location Change'), ('production', 'Production'), ('scrap', 'Scrap'), ('outward', 'Outward'), ('grn', 'New GRN')], max_length=20)),
                ('operation_id', models.BigIntegerField()),
                ('eway_bill_no', models.CharField(max_length=50)),
                ('eway_bill_date', models.DateField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('validity', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'inventory_operation_ewaybills',
                'indexes': [models.Index(fields=['operation_type', 'operation_id'], name='inventory_o_operati_d7d77e_idx')],
            },
        ),
    ]
