# Generated by Django 5.0.14 on 2026-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryoperationconsumption_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymastergrn',
            name='start_from',
            field=models.IntegerField(default=1, help_text='Start from number'),
        ),
        migrations.AddField(
            model_name='inventorymasterissueslip',
            name='start_from',
            field=models.IntegerField(default=1, help_text='Start from number'),
        ),
        migrations.AddField(
            model_name='inventoryoperationscrap',
            name='issue_slip_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymastergrn',
            name='required_digits',
            field=models.IntegerField(default=4, help_text='Required Digits'),
        ),
    ]
