# Generated by Django 5.0.14 on 2026-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorymastergrn_start_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOperationDeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('operation_type', models.CharField(choices=[('jobwork', 'Job Work'), ('interunit', 'Inter Unit'), ('location_change', 'Location Change'), ('production', 'Production'), ('scrap', 'Scrap'), ('outward', 'Outward'), ('grn', 'New GRN')], max_length=20)),
                ('operation_id', models.BigIntegerField()),
                ('dispatch_from', models.TextField(blank=True, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('dispatch_time', models.TimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=15, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lr_gr_consignment', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_bill_date', models.DateField(blank=True, null=True)),
                ('ship_port_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vessel_flight_no', models.CharField(blank=True, max_length=100, null=True)),
                ('port_of_loading', models.CharField(blank=True, max_length=255, null=True)),
                ('port_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('final_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=255, null=True)),
                ('dest_country', models.CharField(blank=True, max_length=255, null=True)),
                ('railway_receipt_no', models.CharField(blank=True, max_length=100, null=True)),
                ('railway_receipt_date', models.DateField(blank=True, null=True)),
                ('fnr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rail_no', models.CharField(blank=True, max_length=100, null=True)),
                ('station_of_loading', models.CharField(blank=True, max_length=255, null=True)),
                ('station_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_document', models.FileField(blank=True, null=True, upload_to='inventory_dispatch/')),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'inventory_operation_delivery_challans',
                'indexes': [models.Index(fields=['operation_type', 'operation_id'], name='inventory_o_operati_458d2c_idx')],
            },
        ),
    ]
