export const SERVICE_UOM_LIST = [
  { code: 'HRS', description: 'Hours' },
  { code: 'DAY', description: 'Day' },
  { code: 'MDY', description: 'Man Day' },
  { code: 'MTH', description: 'Month' },
  { code: 'YRS', description: 'Year' },
  { code: 'MIN', description: 'Minutes' },
  { code: 'VST', description: 'Visit' },
  { code: 'SES', description: 'Session' },
  { code: 'TRP', description: 'Trip' },
  { code: 'LIC', description: 'License' },
  { code: 'GB', description: 'Gigabyte' },
  { code: 'KWD', description: 'Keyword' },
  { code: 'SQFT', description: 'Square Feet' },
  { code: 'MTR', description: 'Metres' },
  { code: 'CBM', description: 'Cubic Meters' },
  { code: 'KMS', description: 'Kilometers' },
  { code: 'PAX', description: 'Person' },
  { code: 'NIT', description: 'Night' },
  { code: 'MHR', description: 'Machine Hours' },
  { code: 'SHF', description: 'Shift' },
  { code: 'BCH', description: 'Batch' },
  { code: 'MNH', description: 'Man Hours' }
];
