# Generated by Django 5.0.14 on 2026-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_address_line1',
            field=models.CharField(blank=True, help_text='Branch address line 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_address_line2',
            field=models.CharField(blank=True, help_text='Branch address line 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_address_line3',
            field=models.CharField(blank=True, help_text='Branch address line 3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastergstdetails',
            name='branch_address',
            field=models.TextField(blank=True, help_text='Branch address (Combined)', null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tcs_section_applicable',
            field=models.CharField(blank=True, help_text='TCS Section Applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section (alternate)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tds_section_applicable',
            field=models.CharField(blank=True, help_text='TDS Section Applicable', max_length=255, null=True),
        ),
    ]
