# Generated by Django 5.0.14 on 2026-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_voucherpurchaseitem_gst_rate_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormasterbasicdetail',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddIndex(
            model_name='vendormasterbasicdetail',
            index=models.Index(fields=['is_deleted'], name='vendor_mast_is_dele_9f7a44_idx'),
        ),
    ]
