# Generated by Django 5.0.14 on 2026-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormastertds',
            name='tcs_section_applicable',
            field=models.CharField(blank=True, help_text='TCS Section Applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section (alternate)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tds_section_applicable',
            field=models.CharField(blank=True, help_text='TDS Section Applicable', max_length=255, null=True),
        ),
    ]
