# Generated by Django 6.0 on 2026-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormasterbasicdetail',
            name='vendor_category',
            field=models.CharField(blank=True, help_text='Vendor category', max_length=200, null=True),
        ),
    ]
