# Generated by Django 5.2.9 on 2026-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastertds',
            name='cin_number',
            field=models.CharField(blank=True, help_text='CIN Number', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='penalty_rate',
            field=models.CharField(blank=True, help_text='Penalty Rate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='tan_number',
            field=models.CharField(blank=True, help_text='TAN Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='tds_rate',
            field=models.CharField(blank=True, help_text='TDS Rate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section (alternate)', max_length=100, null=True),
        ),
    ]
