# Generated by Django 5.0.14 on 2026-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendormasterbasicdetail_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendormasterterms',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit amount', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='vendortransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpo',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax amount', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpo',
            name='total_taxable_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total taxable value', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpo',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total PO value', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpoitem',
            name='final_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final rate', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpoitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST amount', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpoitem',
            name='invoice_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total invoice value', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpoitem',
            name='negotiated_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Negotiated rate', max_digits=25),
        ),
        migrations.AlterField(
            model_name='vendortransactionpoitem',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable value', max_digits=25),
        ),
    ]
