# Generated by Django 5.0.14 on 2026-04-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendormastertds_tcs_section_applicable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendormasterproductservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendormasterproductservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendormasterproductservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendormasterproductservice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendormasterproductservice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vendormasterproductservice',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='vendormasterproductservice',
            name='items',
            field=models.JSONField(default=list, help_text='Deprecated: Use VendorProductServiceItem table'),
        ),
        migrations.AlterModelTable(
            name='vendormasterproductservice',
            table=None,
        ),
        migrations.CreateModel(
            name='VendorProductServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='vendors.vendormasterproductservice')),
            ],
            options={
                'verbose_name': 'Vendor Master Product/Service',
                'verbose_name_plural': 'Vendor Master Products/Services',
                'db_table': 'vendor_master_vendorcreation_productservices',
            },
        ),
    ]
