# Generated by Django 5.0.14 on 2026-04-12 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendormasterproductservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendormasterproductservice',
            options={'verbose_name': 'Vendor Master Product/Service', 'verbose_name_plural': 'Vendor Master Products/Services'},
        ),
        migrations.AlterModelOptions(
            name='vendorproductserviceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendorproductserviceitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorproductserviceitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendorproductserviceitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vendorproductserviceitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vendorproductserviceitem',
            name='vendor_product_service',
        ),
        migrations.AddField(
            model_name='vendormasterproductservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendormasterproductservice',
            name='created_by',
            field=models.CharField(blank=True, help_text='Created by user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendormasterproductservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendormasterproductservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendormasterproductservice',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='product_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_rel', to='vendors.vendormasterproductservice'),
        ),
        migrations.AlterField(
            model_name='vendormasterproductservice',
            name='items',
            field=models.JSONField(default=list, help_text='JSON array of product/service items'),
        ),
        migrations.AlterField(
            model_name='vendorproductserviceitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendorproductserviceitem',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterModelTable(
            name='vendormasterproductservice',
            table='vendor_master_vendorcreation_productservices',
        ),
        migrations.AlterModelTable(
            name='vendorproductserviceitem',
            table='vendor_master_vendorcreation_productservices_items',
        ),
    ]
