# Generated by Django 5.0.14 on 2026-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendormasterproductservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproductserviceitem',
            name='tenant_id',
            field=models.CharField(db_index=True, default='', max_length=36),
        ),
    ]
