# Generated by Django 5.0.14 on 2026-05-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendortransactionpo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortransactionpo',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Mailed', 'Mailed'), ('Closed', 'Closed')], default='Draft', help_text='PO Status', max_length=50),
        ),
    ]
