# Generated by Django 5.0.14 on 2026-04-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorproductserviceitem_tenant_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendormasterproductservice',
            table='vendors_vendormasterproductservice',
        ),
    ]
