# Generated by Django 5.0.14 on 2026-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendortransactionpo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastertds',
            name='tcs_section',
            field=models.CharField(blank=True, help_text='TCS Section (alternate)', max_length=500, null=True),
        ),
    ]
