# Generated by Django 5.0.14 on 2026-06-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendormastertds_tcs_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorproductserviceitem',
            name='vendor_basic_detail',
            field=models.ForeignKey(blank=True, db_column='vendor_basic_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_service_items', to='vendors.vendormasterbasicdetail'),
        ),
    ]
