# Generated by Django 5.0.14 on 2026-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_merge_vendor_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormastertds',
            name='tcs_section_applicable',
            field=models.CharField(blank=True, help_text='TCS Section Applicable', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastertds',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section (alternate)', max_length=500, null=True),
        ),
    ]
