# Generated by Django 5.0.14 on 2026-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_vendormastertds_tcs_section_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortransaction',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendortransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
