# Generated by Django 5.0.14 on 2026-02-04 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Role name (e.g., Accountant)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('permissions', models.JSONField(default=dict, help_text='Hierarchical permissions structure (page -> tabs)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
            ],
            options={
                'db_table': 'rbac_roles',
                'ordering': ['name'],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(blank=True, help_text='Snapshot of username', max_length=150, null=True)),
                ('email', models.CharField(blank=True, help_text='Snapshot of email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Snapshot of phone', max_length=15, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When role was assigned')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned_by_user', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='rbac.role')),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_user_roles',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role', 'tenant_id')},
            },
        ),
    ]
