# Generated by Django 5.0.14 on 2026-04-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrole',
            name='access_expiry',
            field=models.DateTimeField(blank=True, help_text='Access expiration date', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this account is active'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for RBAC users', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='email',
            field=models.CharField(blank=True, help_text='Email of user', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone of user', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User assigned to this role (Optional if RBAC-only user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(blank=True, help_text='Username for login', max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('tenant_id', 'username', 'role')},
        ),
    ]
