# Generated by Django 5.0.14 on 2026-04-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_userrole_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'tenant_id')},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='email',
            field=models.CharField(blank=True, help_text='Snapshot of email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='phone',
            field=models.CharField(blank=True, help_text='Snapshot of phone', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(blank=True, help_text='Snapshot of username', max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='access_expiry',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='password',
        ),
    ]
