# Generated by Django 5.0.14 on 2026-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_userrole_unique_together_alter_userrole_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
