# Generated by Django 5.0.14 on 2026-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_count', models.IntegerField()),
                ('transactions_json', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bank_statement_staging',
                'ordering': ['-uploaded_at'],
                'unique_together': {('tenant_id', 'file_name', 'account_id')},
            },
        ),
    ]
