# Generated by Django 5.0.14 on 2026-03-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInvoiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=64, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('segmentation_done', models.BooleanField(default=False)),
                ('timeout_rate', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulk_invoice_jobs',
            },
        ),
        migrations.CreateModel(
            name='InvoiceProcessingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('skipped', 'Skipped (blank)')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('parent_item_id', models.BigIntegerField(null=True)),
                ('page_number', models.IntegerField(default=1)),
                ('page_count', models.IntegerField(default=1)),
                ('result_json', models.JSONField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('processed_pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.bulkinvoicejob')),
            ],
            options={
                'db_table': 'invoice_processing_items',
            },
        ),
    ]
