# Generated by Django 5.0.14 on 2026-03-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInvoiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('upload_session_id', models.CharField(max_length=255, null=True)),
                ('file_hash', models.CharField(max_length=64, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('segmentation_done', models.BooleanField(default=False)),
                ('timeout_rate', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulk_invoice_jobs',
            },
        ),
        migrations.CreateModel(
            name='InvoiceOCRTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('upload_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_type', models.CharField(default='PURCHASE', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('validation_status', models.CharField(default='PENDING', max_length=50)),
                ('vendor_status', models.CharField(default='PENDING', max_length=50)),
                ('matched_by', models.CharField(blank=True, max_length=100, null=True)),
                ('conflict_message', models.TextField(blank=True, null=True)),
                ('vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('voucher_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=20)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('selected_by', models.CharField(default='FALLBACK', max_length=50)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('version_rank', models.IntegerField(default=99)),
                ('is_primary', models.BooleanField(default=False)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invoice OCR Staging Item',
                'db_table': 'invoice_ocr_temp',
                'unique_together': {('tenant_id', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceProcessingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('skipped', 'Skipped (blank)')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('parent_item_id', models.BigIntegerField(null=True)),
                ('page_number', models.IntegerField(default=1)),
                ('page_count', models.IntegerField(default=1)),
                ('result_json', models.JSONField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('processed_pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.bulkinvoicejob')),
            ],
            options={
                'db_table': 'invoice_processing_items',
            },
        ),
    ]
