# Generated by Django 5.0.14 on 2026-04-09 06:49

from django.db import migrations, models


def populate_tenant_id(apps, schema_editor):
    InvoiceProcessingItem = apps.get_model('vouchers', 'InvoiceProcessingItem')
    for item in InvoiceProcessingItem.objects.all():
        if item.job:
            item.tenant_id = item.job.tenant_id
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='tenant_id',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(populate_tenant_id),
    ]
