# Generated by Django 5.0.14 on 2026-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceocrtemp',
            unique_together={('tenant_id', 'file_hash', 'upload_session_id')},
        ),
    ]
