# Generated by Django 5.0.14 on 2026-05-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceocrtemp',
            unique_together={('tenant_id', 'file_hash', 'upload_session_id')},
        ),
    ]
