# Generated by Django 5.0.14 on 2026-05-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_invoiceocrtemp_unique_together'),
        ('vouchers', '0002_bulkinvoicejob_is_cancelled_and_more'),
    ]

    operations = [
    ]
