# Generated by Django 5.0.14 on 2026-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_invoiceprocessingitem_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceocrtemp',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
