# Generated by Django 5.0.14 on 2026-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_bulkinvoicejob_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceocrtemp',
            options={'managed': False, 'verbose_name': 'Invoice OCR Staging Item'},
        ),
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='staging_record_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkinvoicejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FINALIZING', 'Finalizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceprocessingitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FINALIZING', 'Finalizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (blank)')], default='PENDING', max_length=20),
        ),
    ]
