# Generated by Django 5.0.14 on 2026-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_invoiceocrtemp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField(unique=True)),
                ('match_score', models.FloatField()),
                ('has_mismatch', models.BooleanField(default=False)),
                ('mismatch_details', models.JSONField(null=True)),
                ('legacy_payload', models.JSONField()),
                ('new_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parity_reports',
            },
        ),
        migrations.CreateModel(
            name='ShadowExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField(db_index=True)),
                ('tenant_id', models.CharField(max_length=100)),
                ('pipeline_type', models.CharField(default='SQS_UNIFIED', max_length=50)),
                ('extracted_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shadow_extraction_results',
            },
        ),
    ]
