# Generated by Django 5.0.14 on 2026-04-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_stagedinvoiceheader_stagedinvoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedinvoiceitem',
            name='header',
        ),
        migrations.DeleteModel(
            name='StagedInvoiceHeader',
        ),
        migrations.DeleteModel(
            name='StagedInvoiceItem',
        ),
    ]
