# Generated by Django 5.0.14 on 2026-05-12 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_add_task_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('active_calls', models.IntegerField(default=0)),
                ('max_concurrent', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gemini_quotas',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(default='INITIATED', max_length=50)),
                ('file_name', models.CharField(max_length=512)),
                ('s3_key', models.CharField(max_length=1024)),
                ('total_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upload_sessions',
            },
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='failed_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='processed_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='ai_units_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceprocessingitem',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='bulkinvoicejob',
            index=models.Index(fields=['status', 'created_at'], name='bulk_invoic_status_e89097_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkinvoicejob',
            index=models.Index(fields=['tenant_id', 'status'], name='bulk_invoic_tenant__fe7294_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceprocessingitem',
            index=models.Index(fields=['job', 'status'], name='invoice_pro_job_id_ad4c49_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceprocessingitem',
            index=models.Index(fields=['tenant_id', 'status'], name='invoice_pro_tenant__49d9df_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceprocessingitem',
            index=models.Index(fields=['status', 'updated_at'], name='invoice_pro_status_9a4154_idx'),
        ),
    ]
