# Generated by Django 5.0.14 on 2026-05-13 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_geminiquota_uploadsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiquota',
            name='bucket_capacity',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='geminiquota',
            name='last_refill_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geminiquota',
            name='refill_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='geminiquota',
            name='tokens',
            field=models.FloatField(default=15.0),
        ),
    ]
