# Generated by Django 5.0.14 on 2026-05-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_merge_20260513_1131'),
        ('vouchers', '0007_geminiquota_bucket_capacity_and_more'),
    ]

    operations = [
    ]
