# Generated by Django 5.0.14 on 2026-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_merge_20260521_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinvoicejob',
            name='upload_type',
            field=models.CharField(default='ZOHO', max_length=50),
        ),
        migrations.AlterField(
            model_name='bulkinvoicejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FINALIZING', 'Finalizing'), ('FINALIZED', 'Finalized'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceprocessingitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FINALIZING', 'Finalizing'), ('FINALIZED', 'Finalized'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (blank)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
