# Generated by Django 5.0.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_bulkinvoicejob_upload_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkinvoicejob',
            name='upload_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
