# Generated by Django 5.0.14 on 2026-06-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_alter_bulkinvoicejob_upload_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeminiQuota',
            new_name='AIQuota',
        ),
    ]
