# Generated by Django 5.0.14 on 2026-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFullInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('tan', models.CharField(blank=True, max_length=10, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('financial_year_start', models.DateField(blank=True, null=True)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_numbering', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_informations',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=36, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('username', 'tenant_id')},
            },
        ),
    ]
