# Generated by Django 5.0.14 on 2026-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_master_user_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
