# Generated by Django 5.0.14 on 2026-02-11 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allow_duplicate_usernames_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
