# Generated by Django 5.0.14 on 2026-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_masteruser_last_login_alter_masteruser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfullinfo',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
