# Generated by Django 5.0.14 on 2026-02-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_companyfullinfo_table_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_used',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
