# Generated by Django 5.0.14 on 2026-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_companyfullinfo_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
