# Generated by Django 5.0.14 on 2026-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_companyfullinfo_company_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
