# Generated by Django 5.0.14 on 2026-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_tenant_company_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
    ]
