# Generated by Django 5.0.14 on 2026-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
