# Generated by Django 5.0.14 on 2026-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenant_address_line3_tenant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
