# Generated by Django 5.0.14 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_masteruser_name_masteruser_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
