# Generated by Django 5.0.14 on 2026-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_masteruser_address_line1_masteruser_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
