# Generated by Django 5.0.14 on 2026-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_masteruser_cin_masteruser_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
